#!/usr/bin/env python3
"""
Generate src/data/audioStatus.ts — a whitelist of discourse slugs that have
both a valid .manifest.json and a .webm file in public/audio/.

Run after audio generation + R2 sync to update the static whitelist used by
the frontend to show Listen buttons without fetching from R2 at page load.

Usage:
  python scripts/generate_audio_status.py          # from local public/audio/
  python scripts/generate_audio_status.py --from-r2 # scan R2 bucket instead
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AUDIO_DIR = REPO_ROOT / "public" / "audio"
OUTPUT_FILE = REPO_ROOT / "src" / "data" / "audioStatus.ts"


def load_dotenv() -> None:
    try:
        from dotenv import load_dotenv as _load
        _load(REPO_ROOT / ".env")
    except ImportError:
        pass


def slugs_from_local() -> list[str]:
    """Find slugs that have both .webm and .manifest.json locally."""
    if not AUDIO_DIR.is_dir():
        return []
    opus = {f.stem for f in AUDIO_DIR.iterdir() if f.suffix == ".webm"}
    manifests = set()
    for f in AUDIO_DIR.iterdir():
        if f.name.endswith(".manifest.json"):
            slug = f.name.removesuffix(".manifest.json")
            try:
                data = json.loads(f.read_text())
                if (
                    isinstance(data.get("version"), (int, float))
                    and isinstance(data.get("paragraphs"), list)
                    and len(data["paragraphs"]) > 0
                ):
                    manifests.add(slug)
            except (json.JSONDecodeError, OSError):
                pass
    return sorted(opus & manifests)


def slugs_from_r2() -> list[str]:
    """Scan R2 bucket for slugs with both files present."""
    import boto3

    account_id = os.environ["R2_ACCOUNT_ID"]
    s3 = boto3.client(
        "s3",
        endpoint_url=f"https://{account_id}.r2.cloudflarestorage.com",
        aws_access_key_id=os.environ["R2_ACCESS_KEY_ID"],
        aws_secret_access_key=os.environ["R2_SECRET_ACCESS_KEY"],
        region_name="auto",
    )
    bucket = os.environ.get("R2_BUCKET", "dhamma-audio")
    paginator = s3.get_paginator("list_objects_v2")
    opus = set()
    manifests = set()
    for page in paginator.paginate(Bucket=bucket):
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if "/" in key:
                continue
            if key.endswith(".webm"):
                opus.add(key.removesuffix(".webm"))
            elif key.endswith(".manifest.json"):
                manifests.add(key.removesuffix(".manifest.json"))
    return sorted(opus & manifests)


def write_status(slugs: list[str]) -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "// Auto-generated by scripts/generate_audio_status.py — do not edit\n"
        f"export const audioSlugs: ReadonlySet<string> = new Set({json.dumps(slugs)});\n"
    )
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"✅ {OUTPUT_FILE.relative_to(REPO_ROOT)}: {len(slugs)} discourse(s)")


def main() -> int:
    load_dotenv()
    parser = argparse.ArgumentParser(description="Generate audioStatus.ts")
    parser.add_argument("--from-r2", action="store_true", help="Scan R2 instead of local files")
    args = parser.parse_args()

    if args.from_r2:
        slugs = slugs_from_r2()
    else:
        slugs = slugs_from_local()

    write_status(slugs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
