import { defineMiddleware } from "astro:middleware";
import { getEnglishEntry } from "./utils/getContentEntry";
import { referenceOnlyRouteSet } from "./utils/referenceOnlyRoutes";
import { routes } from "./utils/routes";

const englishRouteSet = new Set<string>(routes);

/** Top-level path with a single segment, e.g. /mn98 (not /sn1.1.1-2/foo). */
const TOP_LEVEL_SLUG = /^\/[^/]+$/;

/** Canonical Sujato reference URLs, e.g. /mn65/en/sujato. */
const SUJATO_REFERENCE_ROUTE = /^\/([^/]+)\/en\/sujato$/;

/** Subset/paragraph slugs like sn49.1 or sn1.1.1-2 (not collection indexes like sn12). */
const DISCOURSE_SLICE = /^[a-z]+\d[\d]*\.\d/i;

export const onRequest = defineMiddleware(async (context, next) => {
	const { pathname } = context.url;

	if (
		pathname.startsWith("/discourse-ssr/") ||
		pathname.startsWith("/discourse-dynamic/") ||
		pathname.startsWith("/discourse-sujato/")
	) {
		return next();
	}

	const sujatoMatch = pathname.match(SUJATO_REFERENCE_ROUTE);
	if (sujatoMatch) {
		return context.rewrite(
			new URL(`/discourse-sujato/${sujatoMatch[1]}`, context.url),
		);
	}

	if (!TOP_LEVEL_SLUG.test(pathname)) {
		return next();
	}

	const slug = pathname.slice(1);

	if (englishRouteSet.has(slug)) {
		return next();
	}

	if (referenceOnlyRouteSet.has(slug)) {
		// Route lists are regenerated by contentWatcher but middleware may keep stale
		// imports until restart; confirm on disk / content store before SSR fallback.
		const english = await getEnglishEntry(slug);
		if (english) {
			return next();
		}

		return context.rewrite(new URL(`/discourse-ssr/${slug}`, context.url));
	}

	if (DISCOURSE_SLICE.test(slug)) {
		// Prerendered [discourse].astro outranks SSR [...id].astro in production;
		// rewrite to a dedicated SSR segment so partial routes resolve.
		return context.rewrite(new URL(`/discourse-dynamic/${slug}`, context.url));
	}

	return next();
});
