import { defineMiddleware } from "astro:middleware";
import { getEnglishEntry } from "./utils/getContentEntry";
import { referenceOnlyRouteSet } from "./utils/referenceOnlyRoutes";
import { routes } from "./utils/routes";
import { canonicalOnSlug } from "./utils/discover-data";

const englishRouteSet = new Set<string>(routes);

/** Top-level path with a single segment, e.g. /mn98 (not /sn1.1.1-2/foo). */
const TOP_LEVEL_SLUG = /^\/[^/]+$/;

/** Canonical Sujato reference URLs, e.g. /mn65/en/sujato. */
const SUJATO_REFERENCE_ROUTE = /^\/([^/]+)\/en\/sujato$/;

/** Subset/paragraph slugs like sn49.1 or sn1.1.1-2 (not collection indexes like sn12). */
const DISCOURSE_SLICE = /^[a-z]+\d[\d]*\.\d/i;

/** /on/:slug is prerendered with hyphenated slugs only; normalize spaced URLs. */
const ON_ROUTE = /^\/on\/([^/]+)$/;

/**
 * View-state and share params that create alternate URLs of the same page.
 * Prerendered discourses ship static HTML, so a <meta robots> set at build
 * time cannot see these — X-Robots-Tag must be applied on the request
 * (Vercel Edge Middleware in production).
 */
const NOINDEX_VIEW_PARAMS = new Set([
	"pli",
	"pl",
	"voice",
	"theme",
	"layout",
	"viz",
	"trans",
	"ref",
	"enablePaliLookup",
	"q",
]);

function hasNoindexViewParams(url: URL): boolean {
	return [...url.searchParams.keys()].some((key) =>
		NOINDEX_VIEW_PARAMS.has(key),
	);
}

function withNoindexIfNeeded(requestUrl: URL, response: Response): Response {
	if (!hasNoindexViewParams(requestUrl) || response.status >= 300) {
		return response;
	}
	const headers = new Headers(response.headers);
	headers.set("X-Robots-Tag", "noindex, follow");
	return new Response(response.body, {
		status: response.status,
		statusText: response.statusText,
		headers,
	});
}

/** Rewrite target keeps the original query string (view-state params). */
function rewriteURL(path: string, from: URL): URL {
	const target = new URL(path, from);
	target.search = from.search;
	return target;
}

export const onRequest = defineMiddleware(async (context, next) => {
	const { pathname } = context.url;
	const noindexViewState = hasNoindexViewParams(context.url);
	// SSR layouts can read this when a rewrite hides the original query string.
	(context.locals as { wotbNoindexViewState?: boolean }).wotbNoindexViewState =
		noindexViewState;

	const onMatch = pathname.match(ON_ROUTE);
	if (onMatch) {
		const rawSlug = onMatch[1];
		let decoded = rawSlug;
		try {
			decoded = decodeURIComponent(rawSlug);
		} catch {
			/* pathname may already be decoded */
		}
		const canonical = canonicalOnSlug(decoded);
		// Compare against rawSlug too: pathname may keep %20 while decoded has spaces.
		if (rawSlug !== canonical) {
			return context.redirect(
				new URL(`/on/${canonical}`, context.url),
				301,
			);
		}
	}

	if (
		pathname.startsWith("/discourse-ssr/") ||
		pathname.startsWith("/discourse-dynamic/") ||
		pathname.startsWith("/discourse-sujato/")
	) {
		return withNoindexIfNeeded(context.url, await next());
	}

	const sujatoMatch = pathname.match(SUJATO_REFERENCE_ROUTE);
	if (sujatoMatch) {
		return withNoindexIfNeeded(
			context.url,
			await context.rewrite(
				rewriteURL(`/discourse-sujato/${sujatoMatch[1]}`, context.url),
			),
		);
	}

	if (!TOP_LEVEL_SLUG.test(pathname)) {
		return withNoindexIfNeeded(context.url, await next());
	}

	const slug = pathname.slice(1);

	if (englishRouteSet.has(slug)) {
		return withNoindexIfNeeded(context.url, await next());
	}

	if (referenceOnlyRouteSet.has(slug)) {
		// Route lists are regenerated by contentWatcher but middleware may keep stale
		// imports until restart; confirm on disk / content store before SSR fallback.
		const english = await getEnglishEntry(slug);
		if (english) {
			return withNoindexIfNeeded(context.url, await next());
		}

		return withNoindexIfNeeded(
			context.url,
			await context.rewrite(rewriteURL(`/discourse-ssr/${slug}`, context.url)),
		);
	}

	if (DISCOURSE_SLICE.test(slug)) {
		// Prerendered [discourse].astro outranks SSR [...id].astro in production;
		// rewrite to a dedicated SSR segment so partial routes resolve.
		return withNoindexIfNeeded(
			context.url,
			await context.rewrite(
				rewriteURL(`/discourse-dynamic/${slug}`, context.url),
			),
		);
	}

	return withNoindexIfNeeded(context.url, await next());
});
