// This file is auto-generated by scripts/import-sc-structure.mjs — do not edit directly
import type { DirectoryStructure } from "../types/directory";

/** AN vagga sections keyed by book slug. Not collection routes — UI grouping only. */
export const anVaggaSections: Record<string, Record<string, DirectoryStructure>> = {
	"an3": {
		"an3.1-10": {
			"title": "Bālavagga - The Chapter on Fools",
			"description": "The Chapter on Fools in the Book of the Threes, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an3.11-20": {
			"title": "Rathakāravagga - The Chapter on the Chariot-maker",
			"description": "The Chapter on the Chariot-maker in the Book of the Threes, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an3.21-30": {
			"title": "Puggalavagga - The Chapter on Individuals",
			"description": "The Chapter on Individuals in the Book of the Threes, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an3.31-40": {
			"title": "Devadūtavagga - The Chapter on Messengers of the Gods",
			"description": "The Chapter on Messengers of the Gods in the Book of the Threes, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an3.41-50": {
			"title": "Cūḷavagga - A Short Chapter",
			"description": "A Short Chapter in the Book of the Threes, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an3.51-60": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Chapter on Brahmins in the Book of the Threes, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an3.61-70": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Threes, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an3.71-80": {
			"title": "Ānandavagga - The Chapter with Ānanda",
			"description": "The Chapter with Ānanda in the Book of the Threes, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an3.81-91": {
			"title": "Samaṇavagga - The Chapter on Ascetics",
			"description": "The Chapter on Ascetics in the Book of the Threes, containing discourses 81–91.",
			"range": {
				"start": 81,
				"end": 91
			}
		},
		"an3.92-102": {
			"title": "Loṇakapallavagga - The Chapter on a Lump of Salt",
			"description": "The Chapter on a Lump of Salt in the Book of the Threes, containing discourses 92–102.",
			"range": {
				"start": 92,
				"end": 102
			}
		},
		"an3.103-112": {
			"title": "Sambodhavagga - The Chapter on Awakening",
			"description": "The Chapter on Awakening in the Book of the Threes, containing discourses 103–112.",
			"range": {
				"start": 103,
				"end": 112
			}
		},
		"an3.113-122": {
			"title": "Āpāyikavagga - The Chapter on Bound for Loss",
			"description": "The Chapter on Bound for Loss in the Book of the Threes, containing discourses 113–122.",
			"range": {
				"start": 113,
				"end": 122
			}
		},
		"an3.123-132": {
			"title": "Kusināravagga - The Chapter at Kusināra",
			"description": "The Chapter at Kusināra in the Book of the Threes, containing discourses 123–132.",
			"range": {
				"start": 123,
				"end": 132
			}
		},
		"an3.133-145": {
			"title": "Yodhājīvavagga - The Chapter on a Warrior",
			"description": "The Chapter on a Warrior in the Book of the Threes, containing discourses 133–145.",
			"range": {
				"start": 133,
				"end": 145
			}
		},
		"an3.146-155": {
			"title": "Maṅgalavagga - The Chapter on Good Fortune",
			"description": "The Chapter on Good Fortune in the Book of the Threes, containing discourses 146–155.",
			"range": {
				"start": 146,
				"end": 155
			}
		},
		"an3.156-162": {
			"title": "Paṭipadāvagga - The Chapter on Practices",
			"description": "The Chapter on Practices in the Book of the Threes, containing discourses 156–162.",
			"range": {
				"start": 156,
				"end": 162
			}
		},
		"an3.163-182": {
			"title": "Kammapathapeyyāvagga - The Chapter on Ways of Performing Deeds",
			"description": "The Chapter on Ways of Performing Deeds in the Book of the Threes, containing discourses 163–182.",
			"range": {
				"start": 163,
				"end": 182
			}
		},
		"an3.183-352": {
			"title": "Rāgādipeyyālavagga - The Chapter on Abbreviated Texts Beginning with Greed",
			"description": "The Chapter on Abbreviated Texts Beginning with Greed in the Book of the Threes, containing discourses 183–352.",
			"range": {
				"start": 183,
				"end": 352
			}
		}
	},
	"an4": {
		"an4.1-10": {
			"title": "Bhaṇḍāgāmavagga - The Chapter at Wares Village",
			"description": "The Chapter at Wares Village in the Book of the Fours, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an4.11-20": {
			"title": "Caravagga - The Chapter on Walking",
			"description": "The Chapter on Walking in the Book of the Fours, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an4.21-30": {
			"title": "Uruvelāvagga - The Chapter at Uruvelā",
			"description": "The Chapter at Uruvelā in the Book of the Fours, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an4.31-40": {
			"title": "Cakkavagga - The Chapter on Situations",
			"description": "The Chapter on Situations in the Book of the Fours, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an4.41-50": {
			"title": "Rohitassavagga - The Chapter with Rohitassa",
			"description": "The Chapter with Rohitassa in the Book of the Fours, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an4.51-60": {
			"title": "Puññābhisandavagga - The Chapter on Overflowing Merit",
			"description": "The Chapter on Overflowing Merit in the Book of the Fours, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an4.61-70": {
			"title": "Pattakammavagga - The Chapter on Deeds of Substance",
			"description": "The Chapter on Deeds of Substance in the Book of the Fours, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an4.71-80": {
			"title": "Apannakavagga - The Chapter on Unfailing",
			"description": "The Chapter on Unfailing in the Book of the Fours, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an4.81-90": {
			"title": "Macalavagga - The Chapter on Confirmed",
			"description": "The Chapter on Confirmed in the Book of the Fours, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an4.91-100": {
			"title": "Asuravagga - The Chapter on Demons",
			"description": "The Chapter on Demons in the Book of the Fours, containing discourses 91–100.",
			"range": {
				"start": 91,
				"end": 100
			}
		},
		"an4.101-110": {
			"title": "Valāhakavagga - The Chapter on Gods of the Clouds",
			"description": "The Chapter on Gods of the Clouds in the Book of the Fours, containing discourses 101–110.",
			"range": {
				"start": 101,
				"end": 110
			}
		},
		"an4.111-120": {
			"title": "Kesivagga - The Chapter with Kesi",
			"description": "The Chapter with Kesi in the Book of the Fours, containing discourses 111–120.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"an4.121-130": {
			"title": "Bhayavagga - The Chapter on Perils",
			"description": "The Chapter on Perils in the Book of the Fours, containing discourses 121–130.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"an4.131-140": {
			"title": "Puggalavagga - The Chapter on Individuals",
			"description": "The Chapter on Individuals in the Book of the Fours, containing discourses 131–140.",
			"range": {
				"start": 131,
				"end": 140
			}
		},
		"an4.141-150": {
			"title": "Ābhavagga - The Chapter on Brightness",
			"description": "The Chapter on Brightness in the Book of the Fours, containing discourses 141–150.",
			"range": {
				"start": 141,
				"end": 150
			}
		},
		"an4.151-160": {
			"title": "Indriyavagga - The Chapter on Faculties",
			"description": "The Chapter on Faculties in the Book of the Fours, containing discourses 151–160.",
			"range": {
				"start": 151,
				"end": 160
			}
		},
		"an4.161-170": {
			"title": "Paṭipadāvagga - The Chapter on Practice",
			"description": "The Chapter on Practice in the Book of the Fours, containing discourses 161–170.",
			"range": {
				"start": 161,
				"end": 170
			}
		},
		"an4.171-180": {
			"title": "Sañcetaniyavagga - The Chapter on Intention",
			"description": "The Chapter on Intention in the Book of the Fours, containing discourses 171–180.",
			"range": {
				"start": 171,
				"end": 180
			}
		},
		"an4.181-190": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Chapter on Brahmins in the Book of the Fours, containing discourses 181–190.",
			"range": {
				"start": 181,
				"end": 190
			}
		},
		"an4.191-200": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Fours, containing discourses 191–200.",
			"range": {
				"start": 191,
				"end": 200
			}
		},
		"an4.201-210": {
			"title": "Sappurisavagga - The Chapter on a True Person",
			"description": "The Chapter on a True Person in the Book of the Fours, containing discourses 201–210.",
			"range": {
				"start": 201,
				"end": 210
			}
		},
		"an4.211-220": {
			"title": "Parisavagga - The Chapter on Assemblies",
			"description": "The Chapter on Assemblies in the Book of the Fours, containing discourses 211–220.",
			"range": {
				"start": 211,
				"end": 220
			}
		},
		"an4.221-231": {
			"title": "Duccaritavagga - The Chapter on Bad Conduct",
			"description": "The Chapter on Bad Conduct in the Book of the Fours, containing discourses 221–231.",
			"range": {
				"start": 221,
				"end": 231
			}
		},
		"an4.232-242": {
			"title": "Kammavagga - The Chapter on Deeds",
			"description": "The Chapter on Deeds in the Book of the Fours, containing discourses 232–242.",
			"range": {
				"start": 232,
				"end": 242
			}
		},
		"an4.243-253": {
			"title": "Āpattibhayavagga - The Chapter on Perils of Offenses",
			"description": "The Chapter on Perils of Offenses in the Book of the Fours, containing discourses 243–253.",
			"range": {
				"start": 243,
				"end": 253
			}
		},
		"an4.254-263": {
			"title": "Abhiññāvagga - The Chapter on Direct Knowledges",
			"description": "The Chapter on Direct Knowledges in the Book of the Fours, containing discourses 254–263.",
			"range": {
				"start": 254,
				"end": 263
			}
		},
		"an4.264-273": {
			"title": "Kammapathavagga - The Chapter on Ways of Performing Deeds",
			"description": "The Chapter on Ways of Performing Deeds in the Book of the Fours, containing discourses 264–273.",
			"range": {
				"start": 264,
				"end": 273
			}
		},
		"an4.274-783": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning with Greed",
			"description": "Abbreviated Texts Beginning with Greed in the Book of the Fours, containing discourses 274–783.",
			"range": {
				"start": 274,
				"end": 783
			}
		}
	},
	"an5": {
		"an5.1-10": {
			"title": "Sekhabalavagga - The Chapter on Powers of a Trainee",
			"description": "The Chapter on Powers of a Trainee in the Book of the Fives, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an5.11-20": {
			"title": "Balavagga - The Chapter on Powers",
			"description": "The Chapter on Powers in the Book of the Fives, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an5.21-30": {
			"title": "Pañcaṅgikavagga - The Chapter on Five Factors",
			"description": "The Chapter on Five Factors in the Book of the Fives, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an5.31-40": {
			"title": "Sumanavagga - The Chapter with Sumanā",
			"description": "The Chapter with Sumanā in the Book of the Fives, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an5.41-50": {
			"title": "Muṇḍarājavagga - The Chapter with King Muṇḍa",
			"description": "The Chapter with King Muṇḍa in the Book of the Fives, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an5.51-60": {
			"title": "Nīvaraṇavagga - The Chapter on Hindrances",
			"description": "The Chapter on Hindrances in the Book of the Fives, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an5.61-70": {
			"title": "Saññāvagga - The Chapter on Perceptions",
			"description": "The Chapter on Perceptions in the Book of the Fives, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an5.71-80": {
			"title": "Yodhājīvavagga - The Chapter on a Warrior",
			"description": "The Chapter on a Warrior in the Book of the Fives, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an5.81-90": {
			"title": "Theravagga - The Chapter on Senior Mendicants",
			"description": "The Chapter on Senior Mendicants in the Book of the Fives, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an5.91-100": {
			"title": "Kakudhavagga - The Chapter with Kakudha",
			"description": "The Chapter with Kakudha in the Book of the Fives, containing discourses 91–100.",
			"range": {
				"start": 91,
				"end": 100
			}
		},
		"an5.101-110": {
			"title": "Phāsuvihāravagga - The Chapter on Living Comfortably",
			"description": "The Chapter on Living Comfortably in the Book of the Fives, containing discourses 101–110.",
			"range": {
				"start": 101,
				"end": 110
			}
		},
		"an5.111-120": {
			"title": "Andhakavindavagga - The Chapter at Andhakavinda",
			"description": "The Chapter at Andhakavinda in the Book of the Fives, containing discourses 111–120.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"an5.121-130": {
			"title": "Gilānavagga - The Chapter on Sick",
			"description": "The Chapter on Sick in the Book of the Fives, containing discourses 121–130.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"an5.131-140": {
			"title": "Rājavagga - The Chapter on Kings",
			"description": "The Chapter on Kings in the Book of the Fives, containing discourses 131–140.",
			"range": {
				"start": 131,
				"end": 140
			}
		},
		"an5.141-150": {
			"title": "Tikaṇḍakīvagga - The Chapter at Tikaṇḍakī",
			"description": "The Chapter at Tikaṇḍakī in the Book of the Fives, containing discourses 141–150.",
			"range": {
				"start": 141,
				"end": 150
			}
		},
		"an5.151-160": {
			"title": "Saddhammavagga - The Chapter on the True Teaching",
			"description": "The Chapter on the True Teaching in the Book of the Fives, containing discourses 151–160.",
			"range": {
				"start": 151,
				"end": 160
			}
		},
		"an5.161-170": {
			"title": "Aghātavagga - The Chapter on Resentment",
			"description": "The Chapter on Resentment in the Book of the Fives, containing discourses 161–170.",
			"range": {
				"start": 161,
				"end": 170
			}
		},
		"an5.171-180": {
			"title": "Upāsakavagga - The Chapter on a Lay Follower",
			"description": "The Chapter on a Lay Follower in the Book of the Fives, containing discourses 171–180.",
			"range": {
				"start": 171,
				"end": 180
			}
		},
		"an5.181-190": {
			"title": "Āraññavagga - The Chapter on Wilderness Dwellers",
			"description": "The Chapter on Wilderness Dwellers in the Book of the Fives, containing discourses 181–190.",
			"range": {
				"start": 181,
				"end": 190
			}
		},
		"an5.191-200": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Chapter on Brahmins in the Book of the Fives, containing discourses 191–200.",
			"range": {
				"start": 191,
				"end": 200
			}
		},
		"an5.201-210": {
			"title": "Kimilavagga - The Chapter with Kimbila",
			"description": "The Chapter with Kimbila in the Book of the Fives, containing discourses 201–210.",
			"range": {
				"start": 201,
				"end": 210
			}
		},
		"an5.211-220": {
			"title": "Akkosakavagga - The Chapter on Abuse",
			"description": "The Chapter on Abuse in the Book of the Fives, containing discourses 211–220.",
			"range": {
				"start": 211,
				"end": 220
			}
		},
		"an5.221-230": {
			"title": "Dīghacārikavagga - The Chapter on Long Wandering",
			"description": "The Chapter on Long Wandering in the Book of the Fives, containing discourses 221–230.",
			"range": {
				"start": 221,
				"end": 230
			}
		},
		"an5.231-240": {
			"title": "Āvāsikavagga - The Chapter on a Resident Mendicant",
			"description": "The Chapter on a Resident Mendicant in the Book of the Fives, containing discourses 231–240.",
			"range": {
				"start": 231,
				"end": 240
			}
		},
		"an5.241-250": {
			"title": "Duccaritavagga - The Chapter on Bad Conduct",
			"description": "The Chapter on Bad Conduct in the Book of the Fives, containing discourses 241–250.",
			"range": {
				"start": 241,
				"end": 250
			}
		},
		"an5.251-271": {
			"title": "Upasampadāvagga - The Chapter on Ordination",
			"description": "The Chapter on Ordination in the Book of the Fives, containing discourses 251–271.",
			"range": {
				"start": 251,
				"end": 271
			}
		},
		"an5.272-285": {
			"title": "Sammutipeyyāla - Abbreviated Texts on Appointments",
			"description": "Abbreviated Texts on Appointments in the Book of the Fives, containing discourses 272–285.",
			"range": {
				"start": 272,
				"end": 285
			}
		},
		"an5.286-302": {
			"title": "Sikkhāpadapeyyāla - Abbreviated Texts on Training Rules",
			"description": "Abbreviated Texts on Training Rules in the Book of the Fives, containing discourses 286–302.",
			"range": {
				"start": 286,
				"end": 302
			}
		},
		"an5.303-1152": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Fives, containing discourses 303–1152.",
			"range": {
				"start": 303,
				"end": 1152
			}
		}
	},
	"an6": {
		"an6.1-10": {
			"title": "Āhuneyyavagga - The Chapter on Worthy of Offerings",
			"description": "The Chapter on Worthy of Offerings in the Book of the Sixes, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an6.11-20": {
			"title": "Sāraṇīyavagga - The Chapter on Warm-hearted",
			"description": "The Chapter on Warm-hearted in the Book of the Sixes, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an6.21-30": {
			"title": "Anuttariyavagga - The Chapter on Unsurpassable",
			"description": "The Chapter on Unsurpassable in the Book of the Sixes, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an6.31-42": {
			"title": "Devatāvagga - The Chapter on Deities",
			"description": "The Chapter on Deities in the Book of the Sixes, containing discourses 31–42.",
			"range": {
				"start": 31,
				"end": 42
			}
		},
		"an6.43-54": {
			"title": "Dhammikavagga - The Chapter with Dhammika",
			"description": "The Chapter with Dhammika in the Book of the Sixes, containing discourses 43–54.",
			"range": {
				"start": 43,
				"end": 54
			}
		},
		"an6.55-64": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Sixes, containing discourses 55–64.",
			"range": {
				"start": 55,
				"end": 64
			}
		},
		"an6.65-74": {
			"title": "Devatāvagga - The Chapter on Deities",
			"description": "The Chapter on Deities in the Book of the Sixes, containing discourses 65–74.",
			"range": {
				"start": 65,
				"end": 74
			}
		},
		"an6.75-84": {
			"title": "Arahattavagga - The Chapter on Perfection",
			"description": "The Chapter on Perfection in the Book of the Sixes, containing discourses 75–84.",
			"range": {
				"start": 75,
				"end": 84
			}
		},
		"an6.85-95": {
			"title": "Sītivagga - The Chapter on Coolness",
			"description": "The Chapter on Coolness in the Book of the Sixes, containing discourses 85–95.",
			"range": {
				"start": 85,
				"end": 95
			}
		},
		"an6.96-106": {
			"title": "Ānisaṁsavagga - The Chapter on Benefit",
			"description": "The Chapter on Benefit in the Book of the Sixes, containing discourses 96–106.",
			"range": {
				"start": 96,
				"end": 106
			}
		},
		"an6.107-116": {
			"title": "Tikavagga - The Chapter on Triads",
			"description": "The Chapter on Triads in the Book of the Sixes, containing discourses 107–116.",
			"range": {
				"start": 107,
				"end": 116
			}
		},
		"an6.117-139": {
			"title": "Sāmaññavagga - The Chapter on the Ascetic Life",
			"description": "The Chapter on the Ascetic Life in the Book of the Sixes, containing discourses 117–139.",
			"range": {
				"start": 117,
				"end": 139
			}
		},
		"an6.140-649": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Sixes, containing discourses 140–649.",
			"range": {
				"start": 140,
				"end": 649
			}
		}
	},
	"an7": {
		"an7.1-10": {
			"title": "Dhanavagga - The Chapter on Wealth",
			"description": "The Chapter on Wealth in the Book of the Sevens, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an7.11-20": {
			"title": "Anusayavagga - The Chapter on Tendencies",
			"description": "The Chapter on Tendencies in the Book of the Sevens, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an7.21-31": {
			"title": "Vajjisattakavagga - The Chapter on the Vajji Seven",
			"description": "The Chapter on the Vajji Seven in the Book of the Sevens, containing discourses 21–31.",
			"range": {
				"start": 21,
				"end": 31
			}
		},
		"an7.32-43": {
			"title": "Devatāvagga - The Chapter on Deities",
			"description": "The Chapter on Deities in the Book of the Sevens, containing discourses 32–43.",
			"range": {
				"start": 32,
				"end": 43
			}
		},
		"an7.44-53": {
			"title": "Mahāyaññavagga - The Chapter on a Great Sacrifice",
			"description": "The Chapter on a Great Sacrifice in the Book of the Sevens, containing discourses 44–53.",
			"range": {
				"start": 44,
				"end": 53
			}
		},
		"an7.54-64": {
			"title": "Abyākatavagga - The Chapter on the Undeclared Points",
			"description": "The Chapter on the Undeclared Points in the Book of the Sevens, containing discourses 54–64.",
			"range": {
				"start": 54,
				"end": 64
			}
		},
		"an7.65-74": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Sevens, containing discourses 65–74.",
			"range": {
				"start": 65,
				"end": 74
			}
		},
		"an7.75-84": {
			"title": "Vinayavagga - The Chapter on the Monastic Law",
			"description": "The Chapter on the Monastic Law in the Book of the Sevens, containing discourses 75–84.",
			"range": {
				"start": 75,
				"end": 84
			}
		},
		"an7.85-94": {
			"title": "Samaṇavagga - The Chapter on Ascetics",
			"description": "The Chapter on Ascetics in the Book of the Sevens, containing discourses 85–94.",
			"range": {
				"start": 85,
				"end": 94
			}
		},
		"an7.95-614": {
			"title": "Āhuneyyavagga - The Chapter on Worthy of Offerings",
			"description": "The Chapter on Worthy of Offerings in the Book of the Sevens, containing discourses 95–96.",
			"range": {
				"start": 95,
				"end": 614
			}
		},
		"an7.615-1124": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Sevens, containing discourses 615–645.",
			"range": {
				"start": 615,
				"end": 1124
			}
		}
	},
	"an8": {
		"an8.1-10": {
			"title": "Mettāvagga - The Chapter on Love",
			"description": "The Chapter on Love in the Book of the Eights, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an8.11-20": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Eights, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an8.21-30": {
			"title": "Gahapativagga - The Chapter on Householders",
			"description": "The Chapter on Householders in the Book of the Eights, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an8.31-40": {
			"title": "Dānavagga - The Chapter on Giving",
			"description": "The Chapter on Giving in the Book of the Eights, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an8.41-50": {
			"title": "Uposathavagga - The Chapter on Sabbath",
			"description": "The Chapter on Sabbath in the Book of the Eights, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an8.51-60": {
			"title": "Gotamīvagga - The Chapter on Gotamī",
			"description": "The Chapter on Gotamī in the Book of the Eights, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an8.61-70": {
			"title": "Bhūmicālavagga - The Chapter on Earthquakes",
			"description": "The Chapter on Earthquakes in the Book of the Eights, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an8.71-80": {
			"title": "Yamakavagga - The Chapter on Pairs",
			"description": "The Chapter on Pairs in the Book of the Eights, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an8.81-90": {
			"title": "Sativagga - The Chapter on Mindfulness",
			"description": "The Chapter on Mindfulness in the Book of the Eights, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an8.91-117": {
			"title": "Sāmaññavagga - The Chapter on Similarity",
			"description": "The Chapter on Similarity in the Book of the Eights, containing discourses 91–91.",
			"range": {
				"start": 91,
				"end": 117
			}
		},
		"an8.118-627": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Eights, containing discourses 118–148.",
			"range": {
				"start": 118,
				"end": 627
			}
		}
	},
	"an9": {
		"an9.1-10": {
			"title": "Sambodhivagga - The Chapter on Awakening",
			"description": "The Chapter on Awakening in the Book of the Nines, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an9.11-20": {
			"title": "Sīhanādavagga - The Chapter on the Lion's Roar",
			"description": "The Chapter on the Lion's Roar in the Book of the Nines, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an9.21-31": {
			"title": "Sattāvāsavagga - The Chapter on Abodes of Sentient Beings",
			"description": "The Chapter on Abodes of Sentient Beings in the Book of the Nines, containing discourses 21–31.",
			"range": {
				"start": 21,
				"end": 31
			}
		},
		"an9.32-41": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Nines, containing discourses 32–41.",
			"range": {
				"start": 32,
				"end": 41
			}
		},
		"an9.42-51": {
			"title": "Sāmaññavagga - The Chapter on Similarity",
			"description": "The Chapter on Similarity in the Book of the Nines, containing discourses 42–51.",
			"range": {
				"start": 42,
				"end": 51
			}
		},
		"an9.52-62": {
			"title": "Khemavagga - The Chapter on a Safe Place",
			"description": "The Chapter on a Safe Place in the Book of the Nines, containing discourses 52–62.",
			"range": {
				"start": 52,
				"end": 62
			}
		},
		"an9.63-72": {
			"title": "Satipaṭṭhānavagga - The Chapter on Mindfulness Meditation",
			"description": "The Chapter on Mindfulness Meditation in the Book of the Nines, containing discourses 63–72.",
			"range": {
				"start": 63,
				"end": 72
			}
		},
		"an9.73-82": {
			"title": "Sammappadhānavagga - The Chapter on Right Efforts",
			"description": "The Chapter on Right Efforts in the Book of the Nines, containing discourses 73–82.",
			"range": {
				"start": 73,
				"end": 82
			}
		},
		"an9.83-92": {
			"title": "Iddhipādavagga - The Chapter on Bases of Psychic Power",
			"description": "The Chapter on Bases of Psychic Power in the Book of the Nines, containing discourses 83–92.",
			"range": {
				"start": 83,
				"end": 92
			}
		},
		"an9.93-432": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Nines, containing discourses 93–113.",
			"range": {
				"start": 93,
				"end": 432
			}
		}
	},
	"an10": {
		"an10.1-10": {
			"title": "Anisamsavagga - The Chapter on Benefits",
			"description": "The Chapter on Benefits in the Book of the Tens, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an10.11-20": {
			"title": "Nāthavagga - The Chapter on a Protector",
			"description": "The Chapter on a Protector in the Book of the Tens, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an10.21-30": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Tens, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an10.31-40": {
			"title": "Upālivagga - The Chapter with Upāli (First Fifty)",
			"description": "The Chapter with Upāli in the first fifty of the Book of the Tens, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an10.41-50": {
			"title": "Akkosavagga - The Chapter on Abuse",
			"description": "The Chapter on Abuse in the Book of the Tens, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an10.51-60": {
			"title": "Sacittavagga - The Chapter on Your Own Mind",
			"description": "The Chapter on Your Own Mind in the Book of the Tens, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an10.61-70": {
			"title": "Yamakavagga - The Chapter on Pairs",
			"description": "The Chapter on Pairs in the Book of the Tens, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an10.71-80": {
			"title": "Ākaṅkhavagga - The Chapter on If You Want",
			"description": "The Chapter on If You Want in the Book of the Tens, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an10.81-90": {
			"title": "Theravagga - The Chapter on Senior Mendicants",
			"description": "The Chapter on Senior Mendicants in the Book of the Tens, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an10.91-100": {
			"title": "Upālivagga - The Chapter with Upāli (Second Fifty)",
			"description": "The Chapter with Upāli in the second fifty of the Book of the Tens, containing discourses 91–100.",
			"range": {
				"start": 91,
				"end": 100
			}
		},
		"an10.101-112": {
			"title": "Samaṇasaññāvagga - The Chapter on Perceptions for Ascetics",
			"description": "The Chapter on Perceptions for Ascetics in the Book of the Tens, containing discourses 101–112.",
			"range": {
				"start": 101,
				"end": 112
			}
		},
		"an10.113-122": {
			"title": "Paccorohaṇivagga - The Chapter on the Ceremony of Descent",
			"description": "The Chapter on the Ceremony of Descent in the Book of the Tens, containing discourses 113–122.",
			"range": {
				"start": 113,
				"end": 122
			}
		},
		"an10.123-133": {
			"title": "Parisuddhavagga - The Chapter on Purified",
			"description": "The Chapter on Purified in the Book of the Tens, containing discourses 123–133.",
			"range": {
				"start": 123,
				"end": 133
			}
		},
		"an10.134-144": {
			"title": "Sādhuvagga - The Chapter on Good (Third Fifty)",
			"description": "The Chapter on Good in the third fifty of the Book of the Tens, containing discourses 134–144.",
			"range": {
				"start": 134,
				"end": 144
			}
		},
		"an10.145-154": {
			"title": "Ariyavagga - The Chapter on the Noble Path",
			"description": "The Chapter on the Noble Path in the Book of the Tens, containing discourses 145–154.",
			"range": {
				"start": 145,
				"end": 154
			}
		},
		"an10.155-166": {
			"title": "Puggalavagga - The Chapter on Individuals",
			"description": "The Chapter on Individuals in the Book of the Tens, containing discourses 155–156.",
			"range": {
				"start": 155,
				"end": 166
			}
		},
		"an10.167-177": {
			"title": "Jāṇussoṇivagga - The Chapter with Jānussoṇi",
			"description": "The Chapter with Jānussoṇi in the Book of the Tens, containing discourses 167–177.",
			"range": {
				"start": 167,
				"end": 177
			}
		},
		"an10.178-188": {
			"title": "Sādhuvagga - The Chapter on Good (Fourth Fifty)",
			"description": "The Chapter on Good in the fourth fifty of the Book of the Tens, containing discourses 178–188.",
			"range": {
				"start": 178,
				"end": 188
			}
		},
		"an10.189-198": {
			"title": "Ariyamaggavagga - The Chapter on the Noble Path",
			"description": "The Chapter on the Noble Path in the Book of the Tens, containing discourses 189–198.",
			"range": {
				"start": 189,
				"end": 198
			}
		},
		"an10.199-210": {
			"title": "Ariyapuggalavagga - Another Chapter on Individuals",
			"description": "Another Chapter on Individuals in the Book of the Tens, containing discourses 199–199.",
			"range": {
				"start": 199,
				"end": 210
			}
		},
		"an10.211-220": {
			"title": "Karajakāyavagga - The Chapter on the Body Born of Deeds",
			"description": "The Chapter on the Body Born of Deeds in the Book of the Tens, containing discourses 211–220.",
			"range": {
				"start": 211,
				"end": 220
			}
		},
		"an10.221-236": {
			"title": "Sāmaññavagga - The Chapter on Similarity",
			"description": "The Chapter on Similarity in the Book of the Tens, containing discourses 221–233.",
			"range": {
				"start": 221,
				"end": 236
			}
		},
		"an10.237-746": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Tens, containing discourses 237–267.",
			"range": {
				"start": 237,
				"end": 746
			}
		}
	},
	"an11": {
		"an11.1-10": {
			"title": "Nissayavagga - The Chapter on Dependence",
			"description": "The Chapter on Dependence in the Book of the Elevens, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an11.11-21": {
			"title": "Anussativagga - The Chapter on Recollection",
			"description": "The Chapter on Recollection in the Book of the Elevens, containing discourses 11–21.",
			"range": {
				"start": 11,
				"end": 21
			}
		},
		"an11.22-981": {
			"title": "Sāmaññavagga - The Chapter on Similarity",
			"description": "The Chapter on Similarity in the Book of the Elevens, containing discourses 22–502.",
			"range": {
				"start": 22,
				"end": 981
			}
		},
		"an11.982-1151": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Elevens, containing discourses 982–992.",
			"range": {
				"start": 982,
				"end": 1151
			}
		}
	}
};
