// This file is auto-generated by scripts/import-sc-structure.mjs — do not edit directly
import type { DirectoryStructure } from "../types/directory";

/** AN vagga sections for pilot books (an4, an5). Not collection routes — UI grouping only. */
export const anVaggaSections: Record<string, Record<string, DirectoryStructure>> = {
	"an4": {
		"an4.1-10": {
			"title": "Bhaṇḍāgāmavagga - The Chapter at Wares Village",
			"description": "The Chapter at Wares Village in the Book of the Fours, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an4.11-20": {
			"title": "Caravagga - The Chapter on Walking",
			"description": "The Chapter on Walking in the Book of the Fours, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an4.21-30": {
			"title": "Uruvelāvagga - The Chapter at Uruvelā",
			"description": "The Chapter at Uruvelā in the Book of the Fours, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an4.31-40": {
			"title": "Cakkavagga - The Chapter on Situations",
			"description": "The Chapter on Situations in the Book of the Fours, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an4.41-50": {
			"title": "Rohitassavagga - The Chapter with Rohitassa",
			"description": "The Chapter with Rohitassa in the Book of the Fours, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an4.51-60": {
			"title": "Puññābhisandavagga - The Chapter on Overflowing Merit",
			"description": "The Chapter on Overflowing Merit in the Book of the Fours, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an4.61-70": {
			"title": "Pattakammavagga - The Chapter on Deeds of Substance",
			"description": "The Chapter on Deeds of Substance in the Book of the Fours, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an4.71-80": {
			"title": "Apannakavagga - The Chapter on Unfailing",
			"description": "The Chapter on Unfailing in the Book of the Fours, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an4.81-90": {
			"title": "Macalavagga - The Chapter on Confirmed",
			"description": "The Chapter on Confirmed in the Book of the Fours, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an4.91-100": {
			"title": "Asuravagga - The Chapter on Demons",
			"description": "The Chapter on Demons in the Book of the Fours, containing discourses 91–100.",
			"range": {
				"start": 91,
				"end": 100
			}
		},
		"an4.101-110": {
			"title": "Valāhakavagga - The Chapter on Gods of the Clouds",
			"description": "The Chapter on Gods of the Clouds in the Book of the Fours, containing discourses 101–110.",
			"range": {
				"start": 101,
				"end": 110
			}
		},
		"an4.111-120": {
			"title": "Kesivagga - The Chapter with Kesi",
			"description": "The Chapter with Kesi in the Book of the Fours, containing discourses 111–120.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"an4.121-130": {
			"title": "Bhayavagga - The Chapter on Perils",
			"description": "The Chapter on Perils in the Book of the Fours, containing discourses 121–130.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"an4.131-140": {
			"title": "Puggalavagga - The Chapter on Individuals",
			"description": "The Chapter on Individuals in the Book of the Fours, containing discourses 131–140.",
			"range": {
				"start": 131,
				"end": 140
			}
		},
		"an4.141-150": {
			"title": "Ābhavagga - The Chapter on Brightness",
			"description": "The Chapter on Brightness in the Book of the Fours, containing discourses 141–150.",
			"range": {
				"start": 141,
				"end": 150
			}
		},
		"an4.151-160": {
			"title": "Indriyavagga - The Chapter on Faculties",
			"description": "The Chapter on Faculties in the Book of the Fours, containing discourses 151–160.",
			"range": {
				"start": 151,
				"end": 160
			}
		},
		"an4.161-170": {
			"title": "Paṭipadāvagga - The Chapter on Practice",
			"description": "The Chapter on Practice in the Book of the Fours, containing discourses 161–170.",
			"range": {
				"start": 161,
				"end": 170
			}
		},
		"an4.171-180": {
			"title": "Sañcetaniyavagga - The Chapter on Intention",
			"description": "The Chapter on Intention in the Book of the Fours, containing discourses 171–180.",
			"range": {
				"start": 171,
				"end": 180
			}
		},
		"an4.181-190": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Chapter on Brahmins in the Book of the Fours, containing discourses 181–190.",
			"range": {
				"start": 181,
				"end": 190
			}
		},
		"an4.191-200": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The Great Chapter in the Book of the Fours, containing discourses 191–200.",
			"range": {
				"start": 191,
				"end": 200
			}
		},
		"an4.201-210": {
			"title": "Sappurisavagga - The Chapter on a True Person",
			"description": "The Chapter on a True Person in the Book of the Fours, containing discourses 201–210.",
			"range": {
				"start": 201,
				"end": 210
			}
		},
		"an4.211-220": {
			"title": "Parisavagga - The Chapter on Assemblies",
			"description": "The Chapter on Assemblies in the Book of the Fours, containing discourses 211–220.",
			"range": {
				"start": 211,
				"end": 220
			}
		},
		"an4.221-231": {
			"title": "Duccaritavagga - The Chapter on Bad Conduct",
			"description": "The Chapter on Bad Conduct in the Book of the Fours, containing discourses 221–231.",
			"range": {
				"start": 221,
				"end": 231
			}
		},
		"an4.232-242": {
			"title": "Kammavagga - The Chapter on Deeds",
			"description": "The Chapter on Deeds in the Book of the Fours, containing discourses 232–242.",
			"range": {
				"start": 232,
				"end": 242
			}
		},
		"an4.243-253": {
			"title": "Āpattibhayavagga - The Chapter on Perils of Offenses",
			"description": "The Chapter on Perils of Offenses in the Book of the Fours, containing discourses 243–253.",
			"range": {
				"start": 243,
				"end": 253
			}
		},
		"an4.254-263": {
			"title": "Abhiññāvagga - The Chapter on Direct Knowledges",
			"description": "The Chapter on Direct Knowledges in the Book of the Fours, containing discourses 254–263.",
			"range": {
				"start": 254,
				"end": 263
			}
		},
		"an4.264-273": {
			"title": "Kammapathavagga - The Chapter on Ways of Performing Deeds",
			"description": "The Chapter on Ways of Performing Deeds in the Book of the Fours, containing discourses 264–273.",
			"range": {
				"start": 264,
				"end": 273
			}
		},
		"an4.274-783": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning with Greed",
			"description": "Abbreviated Texts Beginning with Greed in the Book of the Fours, containing discourses 274–783.",
			"range": {
				"start": 274,
				"end": 783
			}
		}
	},
	"an5": {
		"an5.1-10": {
			"title": "Sekhabalavagga - The Chapter on Powers of a Trainee",
			"description": "The Chapter on Powers of a Trainee in the Book of the Fives, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"an5.11-20": {
			"title": "Balavagga - The Chapter on Powers",
			"description": "The Chapter on Powers in the Book of the Fives, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"an5.21-30": {
			"title": "Pañcaṅgikavagga - The Chapter on Five Factors",
			"description": "The Chapter on Five Factors in the Book of the Fives, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"an5.31-40": {
			"title": "Sumanavagga - The Chapter with Sumanā",
			"description": "The Chapter with Sumanā in the Book of the Fives, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"an5.41-50": {
			"title": "Muṇḍarājavagga - The Chapter with King Muṇḍa",
			"description": "The Chapter with King Muṇḍa in the Book of the Fives, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"an5.51-60": {
			"title": "Nīvaraṇavagga - The Chapter on Hindrances",
			"description": "The Chapter on Hindrances in the Book of the Fives, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"an5.61-70": {
			"title": "Saññāvagga - The Chapter on Perceptions",
			"description": "The Chapter on Perceptions in the Book of the Fives, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"an5.71-80": {
			"title": "Yodhājīvavagga - The Chapter on a Warrior",
			"description": "The Chapter on a Warrior in the Book of the Fives, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"an5.81-90": {
			"title": "Theravagga - The Chapter on Senior Mendicants",
			"description": "The Chapter on Senior Mendicants in the Book of the Fives, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"an5.91-100": {
			"title": "Kakudhavagga - The Chapter with Kakudha",
			"description": "The Chapter with Kakudha in the Book of the Fives, containing discourses 91–100.",
			"range": {
				"start": 91,
				"end": 100
			}
		},
		"an5.101-110": {
			"title": "Phāsuvihāravagga - The Chapter on Living Comfortably",
			"description": "The Chapter on Living Comfortably in the Book of the Fives, containing discourses 101–110.",
			"range": {
				"start": 101,
				"end": 110
			}
		},
		"an5.111-120": {
			"title": "Andhakavindavagga - The Chapter at Andhakavinda",
			"description": "The Chapter at Andhakavinda in the Book of the Fives, containing discourses 111–120.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"an5.121-130": {
			"title": "Gilānavagga - The Chapter on Sick",
			"description": "The Chapter on Sick in the Book of the Fives, containing discourses 121–130.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"an5.131-140": {
			"title": "Rājavagga - The Chapter on Kings",
			"description": "The Chapter on Kings in the Book of the Fives, containing discourses 131–140.",
			"range": {
				"start": 131,
				"end": 140
			}
		},
		"an5.141-150": {
			"title": "Tikaṇḍakīvagga - The Chapter at Tikaṇḍakī",
			"description": "The Chapter at Tikaṇḍakī in the Book of the Fives, containing discourses 141–150.",
			"range": {
				"start": 141,
				"end": 150
			}
		},
		"an5.151-160": {
			"title": "Saddhammavagga - The Chapter on the True Teaching",
			"description": "The Chapter on the True Teaching in the Book of the Fives, containing discourses 151–160.",
			"range": {
				"start": 151,
				"end": 160
			}
		},
		"an5.161-170": {
			"title": "Aghātavagga - The Chapter on Resentment",
			"description": "The Chapter on Resentment in the Book of the Fives, containing discourses 161–170.",
			"range": {
				"start": 161,
				"end": 170
			}
		},
		"an5.171-180": {
			"title": "Upāsakavagga - The Chapter on a Lay Follower",
			"description": "The Chapter on a Lay Follower in the Book of the Fives, containing discourses 171–180.",
			"range": {
				"start": 171,
				"end": 180
			}
		},
		"an5.181-190": {
			"title": "Āraññavagga - The Chapter on Wilderness Dwellers",
			"description": "The Chapter on Wilderness Dwellers in the Book of the Fives, containing discourses 181–190.",
			"range": {
				"start": 181,
				"end": 190
			}
		},
		"an5.191-200": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Chapter on Brahmins in the Book of the Fives, containing discourses 191–200.",
			"range": {
				"start": 191,
				"end": 200
			}
		},
		"an5.201-210": {
			"title": "Kimilavagga - The Chapter with Kimbila",
			"description": "The Chapter with Kimbila in the Book of the Fives, containing discourses 201–210.",
			"range": {
				"start": 201,
				"end": 210
			}
		},
		"an5.211-220": {
			"title": "Akkosakavagga - The Chapter on Abuse",
			"description": "The Chapter on Abuse in the Book of the Fives, containing discourses 211–220.",
			"range": {
				"start": 211,
				"end": 220
			}
		},
		"an5.221-230": {
			"title": "Dīghacārikavagga - The Chapter on Long Wandering",
			"description": "The Chapter on Long Wandering in the Book of the Fives, containing discourses 221–230.",
			"range": {
				"start": 221,
				"end": 230
			}
		},
		"an5.231-240": {
			"title": "Āvāsikavagga - The Chapter on a Resident Mendicant",
			"description": "The Chapter on a Resident Mendicant in the Book of the Fives, containing discourses 231–240.",
			"range": {
				"start": 231,
				"end": 240
			}
		},
		"an5.241-250": {
			"title": "Duccaritavagga - The Chapter on Bad Conduct",
			"description": "The Chapter on Bad Conduct in the Book of the Fives, containing discourses 241–250.",
			"range": {
				"start": 241,
				"end": 250
			}
		},
		"an5.251-271": {
			"title": "Upasampadāvagga - The Chapter on Ordination",
			"description": "The Chapter on Ordination in the Book of the Fives, containing discourses 251–271.",
			"range": {
				"start": 251,
				"end": 271
			}
		},
		"an5.272-285": {
			"title": "Sammutipeyyāla - Abbreviated Texts on Appointments",
			"description": "Abbreviated Texts on Appointments in the Book of the Fives, containing discourses 272–285.",
			"range": {
				"start": 272,
				"end": 285
			}
		},
		"an5.286-302": {
			"title": "Sikkhāpadapeyyāla - Abbreviated Texts on Training Rules",
			"description": "Abbreviated Texts on Training Rules in the Book of the Fives, containing discourses 286–302.",
			"range": {
				"start": 286,
				"end": 302
			}
		},
		"an5.303-1152": {
			"title": "Rāgapeyyāla - Abbreviated Texts Beginning With Greed",
			"description": "Abbreviated Texts Beginning With Greed in the Book of the Fives, containing discourses 303–1152.",
			"range": {
				"start": 303,
				"end": 1152
			}
		}
	}
};
