// Auto-generated by scripts/generate_audio_status.py — do not edit
export const audioSlugs: ReadonlySet<string> = new Set(["an10.76", "dhp1-20", "dhp21-32", "dhp33-43", "dhp44-59", "dhp60-75", "dhp76-89", "dhp90-99", "mn1", "mn10", "mn106", "mn2", "mn20", "mn29", "mn37"]);
