// This file is auto-generated by scripts/import-sc-structure.mjs — do not edit directly
import type { DirectoryStructure } from "../types/directory";

/** MN vagga sections keyed by paṇṇāsa slug (mn1-50, mn51-100, mn101-152). UI grouping only — not collection routes. */
export const mnVaggaSections: Record<string, Record<string, DirectoryStructure>> = {
	"mn1-50": {
		"mn1-10": {
			"title": "Mūlapariyāyavagga - The Chapter on the Root of All Things",
			"description": "This chapter, though beginning with the abstruse Mūlapariyāya Sutta, mostly contains foundational teachings and can, as a whole, serve as an introduction to the discourses.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"mn11-20": {
			"title": "Sīhanādavagga - The Chapter on the Lion's Roar",
			"description": "Beginning with two discourses containing a \"lion's roar\", this chapter deals with suffering, community life, and practical meditation advice.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"mn21-30": {
			"title": "Opammavagga - The Chapter of Similes",
			"description": "A diverse chapter including biography, non-violence, not-self, and an influential teaching on the progress of meditation.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"mn31-40": {
			"title": "Mahāyamakavagga - The Greater Chapter on Pairs",
			"description": "Discourses arranged as pairs of longer and shorter texts.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"mn41-50": {
			"title": "Cūḷayamakavagga - The Lesser Chapter on Pairs",
			"description": "A similar arrangement to the previous chapter, with paired longer and shorter discourses on key doctrines.",
			"range": {
				"start": 41,
				"end": 50
			}
		}
	},
	"mn51-100": {
		"mn51-60": {
			"title": "Gahapativagga - The Chapter on Householders",
			"description": "This chapter is addressed to a diverse range of lay people.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"mn61-70": {
			"title": "Bhikkhuvagga - The Chapter on Mendicants",
			"description": "Ten discourses to monks, many of them focusing on matters of discipline.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"mn71-80": {
			"title": "Paribbājakavagga - The Chapter on Wanderers",
			"description": "The Buddha in dialog with ascetics and wanderers.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"mn81-90": {
			"title": "Rājavagga - The Chapter on Kings",
			"description": "Various dialogs with kings and princes, many of whom followed the Buddha.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"mn91-100": {
			"title": "Brāhmaṇavagga - The Chapter on Brahmins",
			"description": "The Buddha engages with the powerful caste of brahmins, contesting their claims to spiritual authority.",
			"range": {
				"start": 91,
				"end": 100
			}
		}
	},
	"mn101-152": {
		"mn101-110": {
			"title": "Devadahavagga - The Chapter Beginning With Devadaha",
			"description": "Diverse teachings opening with the Devadaha Sutta.",
			"range": {
				"start": 101,
				"end": 110
			}
		},
		"mn111-120": {
			"title": "Anupadavagga - The Chapter Beginning with One By One",
			"description": "Many of the discourses in this chapter delve into complex and analytical presentations of core teachings. It includes important discourses on meditation.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"mn121-130": {
			"title": "Suññatavagga - The Chapter Beginning with Emptiness",
			"description": "Named after the first discourses, which deal with emptiness, this chapter presents less analytical and more narrative texts.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"mn131-142": {
			"title": "Vibhaṅgavagga - The Chapter on Analysis",
			"description": "A series of discourses presented as technical analyses of shorter teachings.",
			"range": {
				"start": 131,
				"end": 142
			}
		},
		"mn143-152": {
			"title": "Saḷāyatanavagga - The Chapter on the Six Senses",
			"description": "Most discourses in this chapter deal with the six sense fields.",
			"range": {
				"start": 143,
				"end": 152
			}
		}
	}
};
