// This file is auto-generated by scripts/import-sc-structure.mjs — do not edit directly
import type { DirectoryStructure } from "../types/directory";

/** SN vagga sections keyed by saṁyutta slug. Not collection routes — UI grouping only. */
export const snVaggaSections: Record<string, Record<string, DirectoryStructure>> = {
	"sn1": {
		"sn1-nalavagga": {
			"title": "Naḷavagga - The Chapter on a Reed",
			"description": "The opening chapter of the Connected Discourses with Deities, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn1-nandanavagga": {
			"title": "Nandanavagga - The Chapter at Nandana",
			"description": "The second chapter of the Connected Discourses with Deities, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn1-sattivagga": {
			"title": "Sattivagga - The Chapter on the Sword",
			"description": "The third chapter of the Connected Discourses with Deities, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn1-satullapakayikavagga": {
			"title": "Satullapakāyikavagga - The Chapter on the Host of a Hundred Devas",
			"description": "The fourth chapter of the Connected Discourses with Deities, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn1-adittavagga": {
			"title": "Ādittavagga - The Chapter on Fire",
			"description": "The fifth chapter of the Connected Discourses with Deities, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn1-jaravagga": {
			"title": "Jarāvagga - The Chapter on Old Age",
			"description": "The sixth chapter of the Connected Discourses with Deities, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"sn1-addhavagga": {
			"title": "Addhavagga - The Chapter on the Path",
			"description": "The seventh chapter of the Connected Discourses with Deities, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"sn1-chetvavagga": {
			"title": "Chetvāvagga - The Chapter on Cutting Off",
			"description": "The eighth chapter of the Connected Discourses with Deities, containing discourses 71–81.",
			"range": {
				"start": 71,
				"end": 81
			}
		}
	},
	"sn2": {
		"sn2-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Young Deities, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn2-anathapindikavagga": {
			"title": "Anāthapiṇḍikavagga - The Chapter with Anāthapiṇḍika",
			"description": "The second chapter of the Connected Discourses with Young Deities, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn2-nanatitthiyavagga": {
			"title": "Nānātitthiyavagga - The Chapter on Various Sectarians",
			"description": "The third chapter of the Connected Discourses with Young Deities, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		}
	},
	"sn3": {
		"sn3-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with King Pasenadi of Kosala, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn3-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with King Pasenadi of Kosala, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn3-tatiyavagga": {
			"title": "Tatiyavagga - The Third Chapter",
			"description": "The third chapter of the Connected Discourses with King Pasenadi of Kosala, containing discourses 21–25.",
			"range": {
				"start": 21,
				"end": 25
			}
		}
	},
	"sn4": {
		"sn4-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Māra, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn4-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Māra, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn4-tatiyavagga": {
			"title": "Tatiyavagga - The Third Chapter",
			"description": "The third chapter of the Connected Discourses with Māra, containing discourses 21–25.",
			"range": {
				"start": 21,
				"end": 25
			}
		}
	},
	"sn5": {
		"sn5-bhikkhunivagga": {
			"title": "Bhikkhunīvagga - The Chapter on Nuns",
			"description": "The chapter of the Connected Discourses with Bhikkhunīs, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn6": {
		"sn6-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Brahmas, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn6-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Brahmas, containing discourses 11–15.",
			"range": {
				"start": 11,
				"end": 15
			}
		}
	},
	"sn7": {
		"sn7-arahantavagga": {
			"title": "Arahantavagga - The Chapter on the Perfected Ones",
			"description": "The first chapter of the Connected Discourses with Brahmins, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn7-upasakavagga": {
			"title": "Upāsakavagga - The Chapter on a Lay Follower",
			"description": "The second chapter of the Connected Discourses with Brahmins, containing discourses 11–22.",
			"range": {
				"start": 11,
				"end": 22
			}
		}
	},
	"sn8": {
		"sn8-vangisavagga": {
			"title": "Vaṅgīsavagga - The Chapter with Vaṅgīsa",
			"description": "The chapter of the Connected Discourses with Vaṅgīsa, containing discourses 1–12.",
			"range": {
				"start": 1,
				"end": 12
			}
		}
	},
	"sn9": {
		"sn9-vanavagga": {
			"title": "Vanavagga - The Chapter in the Forest",
			"description": "The chapter of the Connected Discourses in the Forest, containing discourses 1–14.",
			"range": {
				"start": 1,
				"end": 14
			}
		}
	},
	"sn10": {
		"sn10-indakavagga": {
			"title": "Indakavagga - The Chapter with Indaka",
			"description": "The chapter of the Connected Discourses with Yakkhas, containing discourses 1–12.",
			"range": {
				"start": 1,
				"end": 12
			}
		}
	},
	"sn11": {
		"sn11-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Sakka, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn11-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Sakka, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn11-tatiyavagga": {
			"title": "Tatiyavagga - The Third Chapter",
			"description": "The third chapter of the Connected Discourses with Sakka, containing discourses 21–25.",
			"range": {
				"start": 21,
				"end": 25
			}
		}
	},
	"sn12": {
		"sn12-buddhavagga": {
			"title": "Buddhavagga - The Chapter on the Buddhas",
			"description": "The first chapter of the Connected Discourses on Causation, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn12-aharavagga": {
			"title": "Āhāravagga - The Chapter on Fuel",
			"description": "The second chapter of the Connected Discourses on Causation, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn12-dasabalavagga": {
			"title": "Dasabalavagga - The Chapter on the Ten Powers",
			"description": "The third chapter of the Connected Discourses on Causation, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn12-kalarakhattiyavagga": {
			"title": "Kaḷārakhattiyavagga - The Chapter with Kaḷāra the Aristocrat",
			"description": "The fourth chapter of the Connected Discourses on Causation, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn12-gahapativagga": {
			"title": "Gahapativagga - The Chapter on Householders",
			"description": "The fifth chapter of the Connected Discourses on Causation, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn12-dukkhavagga": {
			"title": "Dukkhavagga - The Chapter on Suffering",
			"description": "The sixth chapter of the Connected Discourses on Causation, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"sn12-mahavagga": {
			"title": "Mahāvagga - The Great Chapter",
			"description": "The seventh chapter of the Connected Discourses on Causation, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"sn12-samanabrahmanavagga": {
			"title": "Samaṇabrāhmaṇavagga - The Chapter on Ascetics and Brahmins",
			"description": "The eighth chapter of the Connected Discourses on Causation, containing discourses 71–81.",
			"range": {
				"start": 71,
				"end": 81
			}
		},
		"sn12-antarapeyyala": {
			"title": "antarapeyyala",
			"range": {
				"start": 82,
				"end": 213
			}
		}
	},
	"sn13": {
		"sn13-abhisamayavagga": {
			"title": "Abhisamayavagga - The Chapter on Comprehension",
			"description": "The chapter of the Connected Discourses on Complete Comprehension, containing discourses 1–11.",
			"range": {
				"start": 1,
				"end": 11
			}
		}
	},
	"sn14": {
		"sn14-nanattavagga": {
			"title": "Nānattavagga - The Chapter on Diversity",
			"description": "The first chapter of the Connected Discourses on the Elements, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn14-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses on the Elements, containing discourses 11–22.",
			"range": {
				"start": 11,
				"end": 22
			}
		},
		"sn14-kammapathavagga": {
			"title": "Kammapathavagga - The Chapter on Ways of Performing Deeds",
			"description": "The third chapter of the Connected Discourses on the Elements, containing discourses 23–29.",
			"range": {
				"start": 23,
				"end": 29
			}
		},
		"sn14-catutthavagga": {
			"title": "Catutthavagga - The Fourth Chapter",
			"description": "The fourth chapter of the Connected Discourses on the Elements, containing discourses 30–39.",
			"range": {
				"start": 30,
				"end": 39
			}
		}
	},
	"sn15": {
		"sn15-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses on the Inconceivable Beginning, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn15-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses on the Inconceivable Beginning, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		}
	},
	"sn16": {
		"sn16-kassapavagga": {
			"title": "Kassapavagga - The Chapter with Kassapa",
			"description": "The chapter of the Connected Discourses with Kassapa, containing discourses 1–13.",
			"range": {
				"start": 1,
				"end": 13
			}
		}
	},
	"sn17": {
		"sn17-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses on Acquisitions and Respect, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn17-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses on Acquisitions and Respect, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn17-tatiyavagga": {
			"title": "Tatiyavagga - The Third Chapter",
			"description": "The third chapter of the Connected Discourses on Acquisitions and Respect, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn17-catutthavagga": {
			"title": "Catutthavagga - The Fourth Chapter",
			"description": "The fourth chapter of the Connected Discourses on Acquisitions and Respect, containing discourses 31–43.",
			"range": {
				"start": 31,
				"end": 43
			}
		}
	},
	"sn18": {
		"sn18-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Rāhula, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn18-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Rāhula, containing discourses 11–22.",
			"range": {
				"start": 11,
				"end": 22
			}
		}
	},
	"sn19": {
		"sn19-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses with Lakkhaṇa, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn19-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Lakkhaṇa, containing discourses 11–21.",
			"range": {
				"start": 11,
				"end": 21
			}
		}
	},
	"sn20": {
		"sn20-opammavagga": {
			"title": "Opammavagga - The Chapter on the Similes",
			"description": "The chapter of the Connected Discourses with Similes, containing discourses 1–12.",
			"range": {
				"start": 1,
				"end": 12
			}
		}
	},
	"sn21": {
		"sn21-bhikkhuvagga": {
			"title": "Bhikkhuvagga - The Chapter on Monks",
			"description": "The chapter of the Connected Discourses with Bhikkhus, containing discourses 1–12.",
			"range": {
				"start": 1,
				"end": 12
			}
		}
	},
	"sn22": {
		"sn22-nakulapituvagga": {
			"title": "Nakulapituvagga - The Chapter with Nakula's Father",
			"description": "The first chapter of the Connected Discourses on the Aggregates, containing discourses 1–11.",
			"range": {
				"start": 1,
				"end": 11
			}
		},
		"sn22-aniccavagga": {
			"title": "Aniccavagga - The Chapter on Impermanence",
			"description": "The second chapter of the Connected Discourses on the Aggregates, containing discourses 12–21.",
			"range": {
				"start": 12,
				"end": 21
			}
		},
		"sn22-bharavagga": {
			"title": "Bhāravagga - The Chapter on the Burden",
			"description": "The third chapter of the Connected Discourses on the Aggregates, containing discourses 22–32.",
			"range": {
				"start": 22,
				"end": 32
			}
		},
		"sn22-natumhakavagga": {
			"title": "Natumhākavagga - The Chapter on \"It's Not Yours\"",
			"description": "The fourth chapter of the Connected Discourses on the Aggregates, containing discourses 33–42.",
			"range": {
				"start": 33,
				"end": 42
			}
		},
		"sn22-attadipavagga": {
			"title": "Attadīpavagga - The Chapter on Being Your Own Island",
			"description": "The fifth chapter of the Connected Discourses on the Aggregates, containing discourses 43–52.",
			"range": {
				"start": 43,
				"end": 52
			}
		},
		"sn22-upayavagga": {
			"title": "Upayavagga - The Chapter on Involvement",
			"description": "The sixth chapter of the Connected Discourses on the Aggregates, containing discourses 53–62.",
			"range": {
				"start": 53,
				"end": 62
			}
		},
		"sn22-arahantavagga": {
			"title": "Arahantavagga - The Chapter on the Perfected Ones",
			"description": "The seventh chapter of the Connected Discourses on the Aggregates, containing discourses 63–72.",
			"range": {
				"start": 63,
				"end": 72
			}
		},
		"sn22-khajjaniyavagga": {
			"title": "Khajjanīyavagga - The Chapter on What Is Edible",
			"description": "The eighth chapter of the Connected Discourses on the Aggregates, containing discourses 73–82.",
			"range": {
				"start": 73,
				"end": 82
			}
		},
		"sn22-theravagga": {
			"title": "Theravagga - The Chapter on Senior Monks",
			"description": "The ninth chapter of the Connected Discourses on the Aggregates, containing discourses 83–92.",
			"range": {
				"start": 83,
				"end": 92
			}
		},
		"sn22-pupphavagga": {
			"title": "Pupphavagga - The Chapter on Flowers",
			"description": "The tenth chapter of the Connected Discourses on the Aggregates, containing discourses 93–102.",
			"range": {
				"start": 93,
				"end": 102
			}
		},
		"sn22-antavagga": {
			"title": "Antavagga - The Chapter on the Ends",
			"description": "The eleventh chapter of the Connected Discourses on the Aggregates, containing discourses 103–112.",
			"range": {
				"start": 103,
				"end": 112
			}
		},
		"sn22-dhammakathikavagga": {
			"title": "Dhammakathikavagga - The Chapter on a Dhamma Speaker",
			"description": "The twelfth chapter of the Connected Discourses on the Aggregates, containing discourses 113–125.",
			"range": {
				"start": 113,
				"end": 125
			}
		},
		"sn22-avijjavagga": {
			"title": "Avijjāvagga - The Chapter on Ignorance",
			"description": "The thirteenth chapter of the Connected Discourses on the Aggregates, containing discourses 126–135.",
			"range": {
				"start": 126,
				"end": 135
			}
		},
		"sn22-kukkulavagga": {
			"title": "Kukkulavagga - The Chapter on Burning Chaff",
			"description": "The fourteenth chapter of the Connected Discourses on the Aggregates, containing discourses 136–149.",
			"range": {
				"start": 136,
				"end": 149
			}
		},
		"sn22-ditthivagga": {
			"title": "Diṭṭhivagga - The Chapter on Views",
			"description": "The fifteenth chapter of the Connected Discourses on the Aggregates, containing discourses 150–159.",
			"range": {
				"start": 150,
				"end": 159
			}
		}
	},
	"sn23": {
		"sn23-pathamamaravagga": {
			"title": "Paṭhamamāravagga - The First Chapter About Māra",
			"description": "The first chapter of the Connected Discourses with Rādha, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn23-dutiyamaravagga": {
			"title": "Dutiyamāravagga - The Second Chapter About Māra",
			"description": "The second chapter of the Connected Discourses with Rādha, containing discourses 11–22.",
			"range": {
				"start": 11,
				"end": 22
			}
		},
		"sn23-ayacanavagga": {
			"title": "Āyācanavagga - The Chapter on Aspiration",
			"description": "The third chapter of the Connected Discourses with Rādha, containing discourses 23–34.",
			"range": {
				"start": 23,
				"end": 34
			}
		},
		"sn23-upanisinnavagga": {
			"title": "Upanisinnavagga - The Chapter on Sitting Close",
			"description": "The fourth chapter of the Connected Discourses with Rādha, containing discourses 35–46.",
			"range": {
				"start": 35,
				"end": 46
			}
		}
	},
	"sn24": {
		"sn24-sotapattivagga": {
			"title": "Sotāpattivagga - The Chapter on Stream-Entry",
			"description": "The first chapter of the Connected Discourses on Views, containing discourses 1–18.",
			"range": {
				"start": 1,
				"end": 18
			}
		},
		"sn24-dutiyagamanavagga": {
			"title": "Dutiyagamanavagga - The Chapter on the Second Round",
			"description": "The second chapter of the Connected Discourses on Views, containing discourses 19–44.",
			"range": {
				"start": 19,
				"end": 44
			}
		},
		"sn24-tatiyagamanavagga": {
			"title": "Tatiyagamanavagga - The Chapter on the Third Round",
			"description": "The third chapter of the Connected Discourses on Views, containing discourses 45–70.",
			"range": {
				"start": 45,
				"end": 70
			}
		},
		"sn24-catutthagamanavagga": {
			"title": "Catutthagamanavagga - The Chapter on the Fourth Round",
			"description": "The fourth chapter of the Connected Discourses on Views, containing discourses 71–96.",
			"range": {
				"start": 71,
				"end": 96
			}
		}
	},
	"sn25": {
		"sn25-cakkhuvagga": {
			"title": "Cakkhuvagga - The Chapter on the Eye",
			"description": "The chapter of the Connected Discourses on Arrival, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn26": {
		"sn26-uppadavagga": {
			"title": "Uppādavagga - The Chapter on Arising",
			"description": "The chapter of the Connected Discourses on Arising, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn27": {
		"sn27-kilesavagga": {
			"title": "Kilesavagga - The Chapter on Corruptions",
			"description": "The chapter of the Connected Discourses on Corruptions, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn28": {
		"sn28-sariputtavagga": {
			"title": "Sāriputtavagga - The Chapter with Sāriputta",
			"description": "The chapter of the Connected Discourses with Sāriputta, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn29": {
		"sn29-nagavagga": {
			"title": "Nāgavagga - The Chapter on Nāgas",
			"description": "The chapter of the Connected Discourses with Nāgas, containing discourses 1–50.",
			"range": {
				"start": 1,
				"end": 50
			}
		}
	},
	"sn30": {
		"sn30-supannavagga": {
			"title": "Supaṇṇavagga - The Chapter on Phoenixes",
			"description": "The chapter of the Connected Discourses with Phoenixes, containing discourses 1–46.",
			"range": {
				"start": 1,
				"end": 46
			}
		}
	},
	"sn31": {
		"sn31-gandhabbavagga": {
			"title": "Gandhabbavagga - The Chapter on Gandhabbas",
			"description": "The chapter of the Connected Discourses with the Gandhabbas, containing discourses 1–112.",
			"range": {
				"start": 1,
				"end": 112
			}
		}
	},
	"sn32": {
		"sn32-valahakavagga": {
			"title": "Valāhakavagga - The Chapter on Gods of the Clouds",
			"description": "The chapter of the Connected Discourses with the Cloud Devas, containing discourses 1–57.",
			"range": {
				"start": 1,
				"end": 57
			}
		}
	},
	"sn33": {
		"sn33-vacchagottavagga": {
			"title": "Vacchagottavagga - The Chapter with Vacchagotta",
			"description": "The chapter of the Connected Discourses with Vacchagotta, containing discourses 1–55.",
			"range": {
				"start": 1,
				"end": 55
			}
		}
	},
	"sn34": {
		"sn34-jhanavagga": {
			"title": "Jhānavagga - The Chapter on Absorption",
			"description": "The chapter of the Connected Discourses on Collectedness (jhāna), containing discourses 1–55.",
			"range": {
				"start": 1,
				"end": 55
			}
		}
	},
	"sn35": {
		"sn35-aniccavagga": {
			"title": "Aniccavagga - The Chapter on Impermanence",
			"description": "The first chapter of the Connected Discourses on the Six Sense Bases, containing discourses 1–12.",
			"range": {
				"start": 1,
				"end": 12
			}
		},
		"sn35-yamakavagga": {
			"title": "Yamakavagga - The Chapter on Pairs",
			"description": "The second chapter of the Connected Discourses on the Six Sense Bases, containing discourses 13–22.",
			"range": {
				"start": 13,
				"end": 22
			}
		},
		"sn35-sabbavagga": {
			"title": "Sabbavagga - The Chapter on All",
			"description": "The third chapter of the Connected Discourses on the Six Sense Bases, containing discourses 23–32.",
			"range": {
				"start": 23,
				"end": 32
			}
		},
		"sn35-jatidhammavagga": {
			"title": "Jātisahavatthuvagga - The Chapter on the Nature of Birth",
			"description": "The fourth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 33–42.",
			"range": {
				"start": 33,
				"end": 42
			}
		},
		"sn35-sabbaaniccavagga": {
			"title": "Sabbaaniccavagga - The Chapter on All is Impermanent",
			"description": "The fifth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 43–52.",
			"range": {
				"start": 43,
				"end": 52
			}
		},
		"sn35-avijjavagga": {
			"title": "Avijjāvagga - The Chapter on Ignorance",
			"description": "The sixth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 53–62.",
			"range": {
				"start": 53,
				"end": 62
			}
		},
		"sn35-migajalavagga": {
			"title": "Migajālavagga - The Chapter with Migajāla",
			"description": "The seventh chapter of the Connected Discourses on the Six Sense Bases, containing discourses 63–73.",
			"range": {
				"start": 63,
				"end": 73
			}
		},
		"sn35-gilanavagga": {
			"title": "Gilānavagga - The Chapter with the Sick",
			"description": "The eighth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 74–83.",
			"range": {
				"start": 74,
				"end": 83
			}
		},
		"sn35-channavagga": {
			"title": "Channavagga - The Chapter with Channa",
			"description": "The ninth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 84–93.",
			"range": {
				"start": 84,
				"end": 93
			}
		},
		"sn35-salavagga": {
			"title": "Sālavagga - The Chapter with Sāla",
			"description": "The tenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 94–103.",
			"range": {
				"start": 94,
				"end": 103
			}
		},
		"sn35-yogakkhemivagga": {
			"title": "Yogakkhemivagga - The Chapter on Security from Bondage",
			"description": "The eleventh chapter of the Connected Discourses on the Six Sense Bases, containing discourses 104–113.",
			"range": {
				"start": 104,
				"end": 113
			}
		},
		"sn35-lokakamagunavagga": {
			"title": "Lokakāmaguṇavagga - The Chapter on Worldly Enjoyments",
			"description": "The twelfth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 114–123.",
			"range": {
				"start": 114,
				"end": 123
			}
		},
		"sn35-gahapativagga": {
			"title": "Gahapativagga - The Chapter on Householders",
			"description": "The thirteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 124–133.",
			"range": {
				"start": 124,
				"end": 133
			}
		},
		"sn35-devadahavagga": {
			"title": "Devadahavagga - The Chapter at Devadaha",
			"description": "The fourteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 134–145.",
			"range": {
				"start": 134,
				"end": 145
			}
		},
		"sn35-navapuranavagga": {
			"title": "Navapuranavagga - The Chapter on the New and the Old",
			"description": "The fifteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 146–155.",
			"range": {
				"start": 146,
				"end": 155
			}
		},
		"sn35-nandikkhayavagga": {
			"title": "Nandikkhayavagga - The Chapter on the Destruction of Craving",
			"description": "The sixteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 156–167.",
			"range": {
				"start": 156,
				"end": 167
			}
		},
		"sn35-satthipeyyalavagga": {
			"title": "Satthipeyyālavagga - The Chapter with the Teacher Repetitions",
			"description": "The seventeenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 168–227.",
			"range": {
				"start": 168,
				"end": 227
			}
		},
		"sn35-samuddavagga": {
			"title": "Samuddavagga - The Chapter with the Ocean Simile",
			"description": "The eighteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 228–237.",
			"range": {
				"start": 228,
				"end": 237
			}
		},
		"sn35-asivisavagga": {
			"title": "Asivisavagga - The Chapter with the Vipers Simile",
			"description": "The nineteenth chapter of the Connected Discourses on the Six Sense Bases, containing discourses 238–248.",
			"range": {
				"start": 238,
				"end": 248
			}
		}
	},
	"sn36": {
		"sn36-sagathavagga": {
			"title": "Sagāthavagga - The Chapter with Verses",
			"description": "The first chapter of the Connected Discourses on Feelings, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn36-rahogatavagga": {
			"title": "Rahogatavagga - The Chapter Spoken Privately",
			"description": "The second chapter of the Connected Discourses on Feelings, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn36-atthasatapariyayavagga": {
			"title": "Aṭṭhasatapariyāyavagga - The Chapter on the Hundred-and-Eightfold Exposition",
			"description": "The third chapter of the Connected Discourses on Feelings, containing discourses 21–31.",
			"range": {
				"start": 21,
				"end": 31
			}
		}
	},
	"sn37": {
		"sn37-pathamapeyyalavagga": {
			"title": "Paṭhamapeyyālavagga - The First Repetition Series",
			"description": "The first chapter of the Connected Discourses on Women, containing discourses 1–14.",
			"range": {
				"start": 1,
				"end": 14
			}
		},
		"sn37-dutiyapeyyalavagga": {
			"title": "Dutiyapeyyālavagga - The Second Repetition Series",
			"description": "The second chapter of the Connected Discourses on Women, containing discourses 15–24.",
			"range": {
				"start": 15,
				"end": 24
			}
		},
		"sn37-balavagga": {
			"title": "Bālavagga - The Chapter on Powers",
			"description": "The third chapter of the Connected Discourses on Women, containing discourses 25–34.",
			"range": {
				"start": 25,
				"end": 34
			}
		}
	},
	"sn38": {
		"sn38-jambukhadakavagga": {
			"title": "Jambukhādakavagga - The Chapter with Jambukhādaka",
			"description": "The chapter of the Connected Discourses with Jambukhādaka, containing discourses 1–16.",
			"range": {
				"start": 1,
				"end": 16
			}
		}
	},
	"sn39": {
		"sn39-samandakavagga": {
			"title": "Sāmaṇḍakavagga - The Chapter with Sāmaṇḍaka",
			"description": "The chapter of the Connected Discourses with Sāmaṇḍaka, containing discourses 1–16.",
			"range": {
				"start": 1,
				"end": 16
			}
		}
	},
	"sn40": {
		"sn40-moggallanavagga": {
			"title": "Moggallānavagga - The Chapter with Moggallāna",
			"description": "The chapter of the Connected Discourses with Moggallāna, containing discourses 1–11.",
			"range": {
				"start": 1,
				"end": 11
			}
		}
	},
	"sn41": {
		"sn41-cittavagga": {
			"title": "Cittavagga - The Chapter with Citta",
			"description": "The chapter of the Connected Discourses with Citta the Householder, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		}
	},
	"sn42": {
		"sn42-gamanivagga": {
			"title": "Gāmaṇivagga - The Chapter with Headmen",
			"description": "The chapter of the Connected Discourses with Headmen, containing discourses 1–13.",
			"range": {
				"start": 1,
				"end": 13
			}
		}
	},
	"sn43": {
		"sn43-pathamavagga": {
			"title": "Paṭhamavagga - The First Chapter",
			"description": "The first chapter of the Connected Discourses on the Unconditioned, containing discourses 1–11.",
			"range": {
				"start": 1,
				"end": 11
			}
		},
		"sn43-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses on the Unconditioned, containing discourses 12–44.",
			"range": {
				"start": 12,
				"end": 44
			}
		}
	},
	"sn44": {
		"sn44-abyakatavagga": {
			"title": "Abyākatavagga - The Chapter on the Undeclared",
			"description": "The chapter of the Connected Discourses on the Undeclared, containing discourses 1–11.",
			"range": {
				"start": 1,
				"end": 11
			}
		}
	},
	"sn45": {
		"sn45-avijjavagga": {
			"title": "Avijjāvagga - The Chapter on Ignorance",
			"description": "The first chapter of the Connected Discourses on the Eightfold Path, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn45-viharavagga": {
			"title": "Vihāravagga - The Chapter on Meditation",
			"description": "The second chapter of the Connected Discourses on the Eightfold Path, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn45-micchattavagga": {
			"title": "Micchattavagga - The Chapter on the Wrong Way",
			"description": "The third chapter of the Connected Discourses on the Eightfold Path, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn45-patipattivagga": {
			"title": "Paṭipattivagga - The Chapter on Practice",
			"description": "The fourth chapter of the Connected Discourses on the Eightfold Path, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn45-annatitthiyapeyyalavagga": {
			"title": "Aññatitthiyapeyyālavagga - Abbreviated Texts on Followers of Other Paths",
			"description": "The fifth chapter of the Connected Discourses on the Eightfold Path, containing discourses 41–48.",
			"range": {
				"start": 41,
				"end": 48
			}
		},
		"sn45-suriyapeyyalavagga": {
			"title": "Sūriyapeyyālavagga - Abbreviated Texts on the Sun",
			"description": "The sixth chapter of the Connected Discourses on the Eightfold Path, containing discourses 49–62.",
			"range": {
				"start": 49,
				"end": 62
			}
		},
		"sn45-ekadhammapeyyalavagga": {
			"title": "Ekadhammapeyyālavagga - Abbreviated Texts on One Thing",
			"description": "The seventh chapter of the Connected Discourses on the Eightfold Path, containing discourses 63–76.",
			"range": {
				"start": 63,
				"end": 76
			}
		},
		"sn45-dutiyaekadhammapeyyalavagga": {
			"title": "Dutiyaekadhammapeyyālavagga - Abbreviated Texts on One Thing (2nd)",
			"description": "The eighth chapter of the Connected Discourses on the Eightfold Path, containing discourses 77–90.",
			"range": {
				"start": 77,
				"end": 90
			}
		},
		"sn45-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The ninth chapter of the Connected Discourses on the Eightfold Path, containing discourses 91–98.",
			"range": {
				"start": 91,
				"end": 102
			}
		},
		"sn45-dutiyagangapeyyalavagga": {
			"title": "Dutiyagangāpeyyālavagga - Abbreviated Texts on the Ganges (2nd)",
			"description": "The tenth chapter of the Connected Discourses on the Eightfold Path, containing discourses 103–134.",
			"range": {
				"start": 103,
				"end": 138
			}
		},
		"sn45-appamadapeyyalavagga": {
			"title": "Appamādapeyyālavagga - Abbreviated Texts on Diligence",
			"description": "The eleventh chapter of the Connected Discourses on the Eightfold Path, containing discourses 139–146.",
			"range": {
				"start": 139,
				"end": 148
			}
		},
		"sn45-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - The Chapter on Hard Work",
			"description": "The twelfth chapter of the Connected Discourses on the Eightfold Path, containing discourses 149–160.",
			"range": {
				"start": 149,
				"end": 160
			}
		},
		"sn45-esanavagga": {
			"title": "Esanāvagga - The Chapter on Searches",
			"description": "The thirteenth chapter of the Connected Discourses on the Eightfold Path, containing discourses 161–170.",
			"range": {
				"start": 161,
				"end": 170
			}
		},
		"sn45-oghavagga": {
			"title": "Oghavagga - The Chapter on Floods",
			"description": "The fourteenth chapter of the Connected Discourses on the Eightfold Path, containing discourses 171–180.",
			"range": {
				"start": 171,
				"end": 180
			}
		}
	},
	"sn46": {
		"sn46-pabbatavagga": {
			"title": "Pabbatovagga - The Chapter on Mountains",
			"description": "The first chapter of the Connected Discourses on the Factors of Awakening, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn46-gilanavagga": {
			"title": "Gilānavagga - The Chapter on the Sick",
			"description": "The second chapter of the Connected Discourses on the Factors of Awakening, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn46-udayivagga": {
			"title": "Udāyivagga - The Chapter with Udāyī",
			"description": "The third chapter of the Connected Discourses on the Factors of Awakening, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn46-nivaranavagga": {
			"title": "Nīvaraṇavagga - The Chapter on Hindrances",
			"description": "The fourth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn46-cakkavattivagga": {
			"title": "Cakkavattivagga - The Chapter on a Wheel-Turning Monarch",
			"description": "The fifth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn46-sakacchavagga": {
			"title": "Sākacchavagga - The Chapter on Discussion",
			"description": "The sixth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 51–56.",
			"range": {
				"start": 51,
				"end": 56
			}
		},
		"sn46-anapanavagga": {
			"title": "Ānāpānavagga - The Chapter on Breathing Meditation",
			"description": "The seventh chapter of the Connected Discourses on the Factors of Awakening, containing discourses 57–66.",
			"range": {
				"start": 57,
				"end": 66
			}
		},
		"sn46-nirodhavagga": {
			"title": "Nirodhavagga - The Chapter on Cessation",
			"description": "The eighth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 67–76.",
			"range": {
				"start": 67,
				"end": 76
			}
		},
		"sn46-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The ninth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 77.",
			"range": {
				"start": 77,
				"end": 88
			}
		},
		"sn46-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The tenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 89.",
			"range": {
				"start": 89,
				"end": 98
			}
		},
		"sn46-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The eleventh chapter of the Connected Discourses on the Factors of Awakening, containing discourses 99.",
			"range": {
				"start": 99,
				"end": 110
			}
		},
		"sn46-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The twelfth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 111.",
			"range": {
				"start": 111,
				"end": 120
			}
		},
		"sn46-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The thirteenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 121–130.",
			"range": {
				"start": 121,
				"end": 130
			}
		},
		"sn46-punagangapeyyalavagga": {
			"title": "Punagangāpeyyālavagga - Another Chapter on the Ganges",
			"description": "The fourteenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 131.",
			"range": {
				"start": 131,
				"end": 142
			}
		},
		"sn46-punaappamadavagga": {
			"title": "Punaappamādavagga - Another Chapter on Diligence",
			"description": "The fifteenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 143.",
			"range": {
				"start": 143,
				"end": 152
			}
		},
		"sn46-punabalakaraniyavagga": {
			"title": "Punabalakaraṇīyavagga - Another Chapter on Hard Work",
			"description": "The sixteenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 153.",
			"range": {
				"start": 153,
				"end": 164
			}
		},
		"sn46-punaesanavagga": {
			"title": "Punaesanāvagga - Another Chapter on Searches",
			"description": "The seventeenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 165.",
			"range": {
				"start": 165,
				"end": 174
			}
		},
		"sn46-punaoghavagga": {
			"title": "Punaoghavagga - Another Chapter on Floods",
			"description": "The eighteenth chapter of the Connected Discourses on the Factors of Awakening, containing discourses 175.",
			"range": {
				"start": 175,
				"end": 184
			}
		}
	},
	"sn47": {
		"sn47-ambapalivagga": {
			"title": "Ambapālivagga - The Chapter in Ambapālī's Wood",
			"description": "The first chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn47-nalandavagga": {
			"title": "Nālandāvagga - The Chapter at Nālandā",
			"description": "The second chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn47-silatthitivagga": {
			"title": "Sīlaṭṭhitivagga - The Chapter on Ethics and Duration",
			"description": "The third chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn47-ananussutavagga": {
			"title": "Ananussutavagga - The Chapter on What Was Not Learned Elsewhere",
			"description": "The fourth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn47-amatavagga": {
			"title": "Amatavagga - The Chapter on the Deathless",
			"description": "The fifth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn47-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The sixth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 51.",
			"range": {
				"start": 51,
				"end": 62
			}
		},
		"sn47-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The seventh chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 63.",
			"range": {
				"start": 63,
				"end": 72
			}
		},
		"sn47-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The eighth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 73.",
			"range": {
				"start": 73,
				"end": 84
			}
		},
		"sn47-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The ninth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 85.",
			"range": {
				"start": 85,
				"end": 94
			}
		},
		"sn47-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The tenth chapter of the Connected Discourses on the Establishments of Mindfulness, containing discourses 95.",
			"range": {
				"start": 95,
				"end": 104
			}
		}
	},
	"sn48": {
		"sn48-suddhikavagga": {
			"title": "Suddhikavagga - The Chapter on the Plain Version",
			"description": "The first chapter of the Connected Discourses on the Faculties, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn48-mudutaravagga": {
			"title": "Mudutaravagga - The Chapter on the Weaker Version",
			"description": "The second chapter of the Connected Discourses on the Faculties, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn48-chalindriyavagga": {
			"title": "Chaḷindriyavagga - The Chapter on the Six Faculties",
			"description": "The third chapter of the Connected Discourses on the Faculties, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn48-sukhindriyavagga": {
			"title": "Sukhindriyavagga - The Chapter on the Pleasure Faculty",
			"description": "The fourth chapter of the Connected Discourses on the Faculties, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn48-jaravagga": {
			"title": "Jarāvagga - The Chapter on Old Age",
			"description": "The fifth chapter of the Connected Discourses on the Faculties, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn48-sukarakhatavagga": {
			"title": "Sūkarakhatavagga - The Chapter at the Boar's Cave",
			"description": "The sixth chapter of the Connected Discourses on the Faculties, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"sn48-bodhipakkhiyavagga": {
			"title": "Bodhipakkhiyavagga - The Chapter on Qualities Leading to Awakening",
			"description": "The seventh chapter of the Connected Discourses on the Faculties, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"sn48-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The eighth chapter of the Connected Discourses on the Faculties, containing discourses 71.",
			"range": {
				"start": 71,
				"end": 82
			}
		},
		"sn48-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The ninth chapter of the Connected Discourses on the Faculties, containing discourses 83.",
			"range": {
				"start": 83,
				"end": 92
			}
		},
		"sn48-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The tenth chapter of the Connected Discourses on the Faculties, containing discourses 93.",
			"range": {
				"start": 93,
				"end": 104
			}
		},
		"sn48-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The eleventh chapter of the Connected Discourses on the Faculties, containing discourses 105.",
			"range": {
				"start": 105,
				"end": 114
			}
		},
		"sn48-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The twelfth chapter of the Connected Discourses on the Faculties, containing discourses 115.",
			"range": {
				"start": 115,
				"end": 124
			}
		},
		"sn48-punagangapeyyalavagga": {
			"title": "Punagangāpeyyālavagga - Another Chapter on the Ganges",
			"description": "The thirteenth chapter of the Connected Discourses on the Faculties, containing discourses 125.",
			"range": {
				"start": 125,
				"end": 136
			}
		},
		"sn48-punaappamadavagga": {
			"title": "Punaappamādavagga - Another Chapter on Diligence",
			"description": "The fourteenth chapter of the Connected Discourses on the Faculties, containing discourses 137.",
			"range": {
				"start": 137,
				"end": 146
			}
		},
		"sn48-punabalakaraniyavagga": {
			"title": "Punabalakaraṇīyavagga - Another Chapter on Hard Work",
			"description": "The fifteenth chapter of the Connected Discourses on the Faculties, containing discourses 147.",
			"range": {
				"start": 147,
				"end": 158
			}
		},
		"sn48-punaesanavagga": {
			"title": "Punaesanāvagga - Another Chapter on Searches",
			"description": "The sixteenth chapter of the Connected Discourses on the Faculties, containing discourses 159.",
			"range": {
				"start": 159,
				"end": 168
			}
		},
		"sn48-punaoghavagga": {
			"title": "Punaoghavagga - Another Chapter on Floods",
			"description": "The seventeenth chapter of the Connected Discourses on the Faculties, containing discourses 169.",
			"range": {
				"start": 169,
				"end": 178
			}
		}
	},
	"sn49": {
		"sn49-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The first chapter of the Connected Discourses on the Right Efforts, containing discourses 1.",
			"range": {
				"start": 1,
				"end": 12
			}
		},
		"sn49-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The second chapter of the Connected Discourses on the Right Efforts, containing discourses 13.",
			"range": {
				"start": 13,
				"end": 22
			}
		},
		"sn49-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The third chapter of the Connected Discourses on the Right Efforts, containing discourses 23.",
			"range": {
				"start": 23,
				"end": 34
			}
		},
		"sn49-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The fourth chapter of the Connected Discourses on the Right Efforts, containing discourses 35.",
			"range": {
				"start": 35,
				"end": 44
			}
		},
		"sn49-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The fifth chapter of the Connected Discourses on the Right Efforts, containing discourses 45.",
			"range": {
				"start": 45,
				"end": 54
			}
		}
	},
	"sn50": {
		"sn50-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The first chapter of the Connected Discourses on the Powers, containing discourses 1.",
			"range": {
				"start": 1,
				"end": 12
			}
		},
		"sn50-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The second chapter of the Connected Discourses on the Powers, containing discourses 13.",
			"range": {
				"start": 13,
				"end": 22
			}
		},
		"sn50-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The third chapter of the Connected Discourses on the Powers, containing discourses 23.",
			"range": {
				"start": 23,
				"end": 34
			}
		},
		"sn50-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The fourth chapter of the Connected Discourses on the Powers, containing discourses 35.",
			"range": {
				"start": 35,
				"end": 44
			}
		},
		"sn50-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The fifth chapter of the Connected Discourses on the Powers, containing discourses 45.",
			"range": {
				"start": 45,
				"end": 54
			}
		},
		"sn50-punagangapeyyalavagga": {
			"title": "Punagangāpeyyālavagga - Another Chapter on the Ganges",
			"description": "The sixth chapter of the Connected Discourses on the Powers, containing discourses 55.",
			"range": {
				"start": 55,
				"end": 66
			}
		},
		"sn50-punaappamadavagga": {
			"title": "Punaappamādavagga - Another Chapter on Diligence",
			"description": "The seventh chapter of the Connected Discourses on the Powers, containing discourses 67.",
			"range": {
				"start": 67,
				"end": 76
			}
		},
		"sn50-punabalakaraniyavagga": {
			"title": "Punabalakaraṇīyavagga - Another Chapter on Hard Work",
			"description": "The eighth chapter of the Connected Discourses on the Powers, containing discourses 77.",
			"range": {
				"start": 77,
				"end": 88
			}
		},
		"sn50-punaesanavagga": {
			"title": "Punaesanāvagga - Another Chapter on Searches",
			"description": "The ninth chapter of the Connected Discourses on the Powers, containing discourses 89.",
			"range": {
				"start": 89,
				"end": 98
			}
		},
		"sn50-punaoghavagga": {
			"title": "Punaoghavagga - Another Chapter on Floods",
			"description": "The tenth chapter of the Connected Discourses on the Powers, containing discourses 99.",
			"range": {
				"start": 99,
				"end": 108
			}
		}
	},
	"sn51": {
		"sn51-capalavagga": {
			"title": "Cāpālavagga - The Chapter at the Cāpāla Shrine",
			"description": "The first chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn51-pasadakampanavagga": {
			"title": "Pāsādakampanavagga - The Chapter on Shaking the Stilt Longhouse",
			"description": "The second chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn51-ayogulavagga": {
			"title": "Ayoguḷavagga - The Chapter on the Iron Ball",
			"description": "The third chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 21–32.",
			"range": {
				"start": 21,
				"end": 32
			}
		},
		"sn51-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The fourth chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 33.",
			"range": {
				"start": 33,
				"end": 44
			}
		},
		"sn51-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The fifth chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 45.",
			"range": {
				"start": 45,
				"end": 54
			}
		},
		"sn51-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The sixth chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 55.",
			"range": {
				"start": 55,
				"end": 66
			}
		},
		"sn51-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The seventh chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 67.",
			"range": {
				"start": 67,
				"end": 76
			}
		},
		"sn51-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The eighth chapter of the Connected Discourses on the Bases of Psychic Power, containing discourses 77.",
			"range": {
				"start": 77,
				"end": 86
			}
		}
	},
	"sn52": {
		"sn52-rahogatavagga": {
			"title": "Rahogatavagga - The Chapter in Private",
			"description": "The first chapter of the Connected Discourses with Anuruddha, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn52-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses with Anuruddha, containing discourses 11–24.",
			"range": {
				"start": 11,
				"end": 24
			}
		}
	},
	"sn53": {
		"sn53-gangapeyyalavagga": {
			"title": "Gaṅgāpeyyālavagga - Abbreviated Texts on the Ganges",
			"description": "The first chapter of the Connected Discourses on Collectedness, containing discourses 1.",
			"range": {
				"start": 1,
				"end": 12
			}
		},
		"sn53-appamadavagga": {
			"title": "Appamādavagga - Abbreviated Texts on Diligence",
			"description": "The second chapter of the Connected Discourses on Collectedness, containing discourses 13.",
			"range": {
				"start": 13,
				"end": 22
			}
		},
		"sn53-balakaraniyavagga": {
			"title": "Balakaraṇīyavagga - Abbreviated Texts on Hard Work",
			"description": "The third chapter of the Connected Discourses on Collectedness, containing discourses 23.",
			"range": {
				"start": 23,
				"end": 34
			}
		},
		"sn53-esanavagga": {
			"title": "Esanāvagga - Abbreviated Texts on Searches",
			"description": "The fourth chapter of the Connected Discourses on Collectedness, containing discourses 35.",
			"range": {
				"start": 35,
				"end": 44
			}
		},
		"sn53-oghavagga": {
			"title": "Oghavagga - Abbreviated Texts on Floods",
			"description": "The fifth chapter of the Connected Discourses on Collectedness, containing discourses 45.",
			"range": {
				"start": 45,
				"end": 54
			}
		}
	},
	"sn54": {
		"sn54-ekadhammavagga": {
			"title": "Ekadhammavagga - The Chapter on One Thing",
			"description": "The first chapter of the Connected Discourses on Mindfulness of Breathing, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn54-dutiyavagga": {
			"title": "Dutiyavagga - The Second Chapter",
			"description": "The second chapter of the Connected Discourses on Mindfulness of Breathing, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		}
	},
	"sn55": {
		"sn55-veludvaravagga": {
			"title": "Veḷudvāravagga - The Chapter at Bamboo Gate",
			"description": "The first chapter of the Connected Discourses on Stream-Entry, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn55-rajakaramavagga": {
			"title": "Rājakārāmavagga - The Chapter at the Royal Park",
			"description": "The second chapter of the Connected Discourses on Stream-Entry, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn55-sarananivagga": {
			"title": "Saraṇānivagga - The Chapter on Going for Refuge",
			"description": "The third chapter of the Connected Discourses on Stream-Entry, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn55-punnabhisandavagga": {
			"title": "Puññābhisandavagga - The Chapter on Overflowing Merit",
			"description": "The fourth chapter of the Connected Discourses on Stream-Entry, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn55-sagathakapunnabhisandavagga": {
			"title": "Sagāthakapuññābhisandavagga - The Chapter on Overflowing Merit, With Verses",
			"description": "The fifth chapter of the Connected Discourses on Stream-Entry, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn55-sappannavagga": {
			"title": "Sappaññavagga - The Chapter on a Wise Person",
			"description": "The sixth chapter of the Connected Discourses on Stream-Entry, containing discourses 51–61.",
			"range": {
				"start": 51,
				"end": 61
			}
		},
		"sn55-mahapannavagga": {
			"title": "Mahāpaññavagga - The Chapter on Great Wisdom",
			"description": "The seventh chapter of the Connected Discourses on Stream-Entry, containing discourses 62–74.",
			"range": {
				"start": 62,
				"end": 74
			}
		}
	},
	"sn56": {
		"sn56-samadhivagga": {
			"title": "Samādhivagga - The Chapter on Collectedness",
			"description": "The first chapter of the Connected Discourses on the Truths, containing discourses 1–10.",
			"range": {
				"start": 1,
				"end": 10
			}
		},
		"sn56-dhammacakkappavattanavagga": {
			"title": "Dhammacakkappavattanavagga - The Chapter on Rolling Forth the Wheel of Dhamma",
			"description": "The second chapter of the Connected Discourses on the Truths, containing discourses 11–20.",
			"range": {
				"start": 11,
				"end": 20
			}
		},
		"sn56-kotigamavagga": {
			"title": "Koṭigāmavagga - The Chapter at the Village of Koṭi",
			"description": "The third chapter of the Connected Discourses on the Truths, containing discourses 21–30.",
			"range": {
				"start": 21,
				"end": 30
			}
		},
		"sn56-sisapavanavagga": {
			"title": "Sīsapāvanavagga - The Chapter in a Rosewood Forest",
			"description": "The fourth chapter of the Connected Discourses on the Truths, containing discourses 31–40.",
			"range": {
				"start": 31,
				"end": 40
			}
		},
		"sn56-papatavagga": {
			"title": "Papātavagga - The Chapter on a Cliff",
			"description": "The fifth chapter of the Connected Discourses on the Truths, containing discourses 41–50.",
			"range": {
				"start": 41,
				"end": 50
			}
		},
		"sn56-abhisamayavagga": {
			"title": "Abhisamayavagga - The Chapter on Comprehension",
			"description": "The sixth chapter of the Connected Discourses on the Truths, containing discourses 51–60.",
			"range": {
				"start": 51,
				"end": 60
			}
		},
		"sn56-pathamaamakadhannapeyyalavagga": {
			"title": "Paṭhamaāmakadhannapeyyālavagga - Abbreviated Texts on Raw Grain (1st)",
			"description": "The seventh chapter of the Connected Discourses on the Truths, containing discourses 61–70.",
			"range": {
				"start": 61,
				"end": 70
			}
		},
		"sn56-dutiyaamakadhannapeyyalavagga": {
			"title": "Dutiyaāmakadhannapeyyālavagga - Abbreviated Texts on Raw Grain (2nd)",
			"description": "The eighth chapter of the Connected Discourses on the Truths, containing discourses 71–80.",
			"range": {
				"start": 71,
				"end": 80
			}
		},
		"sn56-tatiyaamakadhannapeyyalavagga": {
			"title": "Tatiyaāmakadhannapeyyālavagga - Abbreviated Texts on Raw Grain (3rd)",
			"description": "The ninth chapter of the Connected Discourses on the Truths, containing discourses 81–90.",
			"range": {
				"start": 81,
				"end": 90
			}
		},
		"sn56-catutthaamakadhannapeyyalavagga": {
			"title": "Catutthaāmakadhannapeyyālavagga - Abbreviated Texts on Raw Grain (4th)",
			"description": "The tenth chapter of the Connected Discourses on the Truths, containing discourses 91–96.",
			"range": {
				"start": 91,
				"end": 101
			}
		},
		"sn56-pancagatipeyyalavagga": {
			"title": "Pañcagatipeyyālavagga - Abbreviated Texts on the Five Destinations",
			"description": "The eleventh chapter of the Connected Discourses on the Truths, containing discourses 102–131.",
			"range": {
				"start": 102,
				"end": 131
			}
		}
	}
};

/** Discourse-range lookup for SN vagga slugs (e.g. sn1-nalavagga → sn1.1–10). */
export const snVaggaRangeBySlug: Record<string, { book: number; start: number; end: number }> = {
	"sn1-nalavagga": {
		"book": 1,
		"start": 1,
		"end": 10
	},
	"sn1-nandanavagga": {
		"book": 1,
		"start": 11,
		"end": 20
	},
	"sn1-sattivagga": {
		"book": 1,
		"start": 21,
		"end": 30
	},
	"sn1-satullapakayikavagga": {
		"book": 1,
		"start": 31,
		"end": 40
	},
	"sn1-adittavagga": {
		"book": 1,
		"start": 41,
		"end": 50
	},
	"sn1-jaravagga": {
		"book": 1,
		"start": 51,
		"end": 60
	},
	"sn1-addhavagga": {
		"book": 1,
		"start": 61,
		"end": 70
	},
	"sn1-chetvavagga": {
		"book": 1,
		"start": 71,
		"end": 81
	},
	"sn2-pathamavagga": {
		"book": 2,
		"start": 1,
		"end": 10
	},
	"sn2-anathapindikavagga": {
		"book": 2,
		"start": 11,
		"end": 20
	},
	"sn2-nanatitthiyavagga": {
		"book": 2,
		"start": 21,
		"end": 30
	},
	"sn3-pathamavagga": {
		"book": 3,
		"start": 1,
		"end": 10
	},
	"sn3-dutiyavagga": {
		"book": 3,
		"start": 11,
		"end": 20
	},
	"sn3-tatiyavagga": {
		"book": 3,
		"start": 21,
		"end": 25
	},
	"sn4-pathamavagga": {
		"book": 4,
		"start": 1,
		"end": 10
	},
	"sn4-dutiyavagga": {
		"book": 4,
		"start": 11,
		"end": 20
	},
	"sn4-tatiyavagga": {
		"book": 4,
		"start": 21,
		"end": 25
	},
	"sn5-bhikkhunivagga": {
		"book": 5,
		"start": 1,
		"end": 10
	},
	"sn6-pathamavagga": {
		"book": 6,
		"start": 1,
		"end": 10
	},
	"sn6-dutiyavagga": {
		"book": 6,
		"start": 11,
		"end": 15
	},
	"sn7-arahantavagga": {
		"book": 7,
		"start": 1,
		"end": 10
	},
	"sn7-upasakavagga": {
		"book": 7,
		"start": 11,
		"end": 22
	},
	"sn8-vangisavagga": {
		"book": 8,
		"start": 1,
		"end": 12
	},
	"sn9-vanavagga": {
		"book": 9,
		"start": 1,
		"end": 14
	},
	"sn10-indakavagga": {
		"book": 10,
		"start": 1,
		"end": 12
	},
	"sn11-pathamavagga": {
		"book": 11,
		"start": 1,
		"end": 10
	},
	"sn11-dutiyavagga": {
		"book": 11,
		"start": 11,
		"end": 20
	},
	"sn11-tatiyavagga": {
		"book": 11,
		"start": 21,
		"end": 25
	},
	"sn12-buddhavagga": {
		"book": 12,
		"start": 1,
		"end": 10
	},
	"sn12-aharavagga": {
		"book": 12,
		"start": 11,
		"end": 20
	},
	"sn12-dasabalavagga": {
		"book": 12,
		"start": 21,
		"end": 30
	},
	"sn12-kalarakhattiyavagga": {
		"book": 12,
		"start": 31,
		"end": 40
	},
	"sn12-gahapativagga": {
		"book": 12,
		"start": 41,
		"end": 50
	},
	"sn12-dukkhavagga": {
		"book": 12,
		"start": 51,
		"end": 60
	},
	"sn12-mahavagga": {
		"book": 12,
		"start": 61,
		"end": 70
	},
	"sn12-samanabrahmanavagga": {
		"book": 12,
		"start": 71,
		"end": 81
	},
	"sn12-antarapeyyala": {
		"book": 12,
		"start": 82,
		"end": 213
	},
	"sn13-abhisamayavagga": {
		"book": 13,
		"start": 1,
		"end": 11
	},
	"sn14-nanattavagga": {
		"book": 14,
		"start": 1,
		"end": 10
	},
	"sn14-dutiyavagga": {
		"book": 14,
		"start": 11,
		"end": 22
	},
	"sn14-kammapathavagga": {
		"book": 14,
		"start": 23,
		"end": 29
	},
	"sn14-catutthavagga": {
		"book": 14,
		"start": 30,
		"end": 39
	},
	"sn15-pathamavagga": {
		"book": 15,
		"start": 1,
		"end": 10
	},
	"sn15-dutiyavagga": {
		"book": 15,
		"start": 11,
		"end": 20
	},
	"sn16-kassapavagga": {
		"book": 16,
		"start": 1,
		"end": 13
	},
	"sn17-pathamavagga": {
		"book": 17,
		"start": 1,
		"end": 10
	},
	"sn17-dutiyavagga": {
		"book": 17,
		"start": 11,
		"end": 20
	},
	"sn17-tatiyavagga": {
		"book": 17,
		"start": 21,
		"end": 30
	},
	"sn17-catutthavagga": {
		"book": 17,
		"start": 31,
		"end": 43
	},
	"sn18-pathamavagga": {
		"book": 18,
		"start": 1,
		"end": 10
	},
	"sn18-dutiyavagga": {
		"book": 18,
		"start": 11,
		"end": 22
	},
	"sn19-pathamavagga": {
		"book": 19,
		"start": 1,
		"end": 10
	},
	"sn19-dutiyavagga": {
		"book": 19,
		"start": 11,
		"end": 21
	},
	"sn20-opammavagga": {
		"book": 20,
		"start": 1,
		"end": 12
	},
	"sn21-bhikkhuvagga": {
		"book": 21,
		"start": 1,
		"end": 12
	},
	"sn22-nakulapituvagga": {
		"book": 22,
		"start": 1,
		"end": 11
	},
	"sn22-aniccavagga": {
		"book": 22,
		"start": 12,
		"end": 21
	},
	"sn22-bharavagga": {
		"book": 22,
		"start": 22,
		"end": 32
	},
	"sn22-natumhakavagga": {
		"book": 22,
		"start": 33,
		"end": 42
	},
	"sn22-attadipavagga": {
		"book": 22,
		"start": 43,
		"end": 52
	},
	"sn22-upayavagga": {
		"book": 22,
		"start": 53,
		"end": 62
	},
	"sn22-arahantavagga": {
		"book": 22,
		"start": 63,
		"end": 72
	},
	"sn22-khajjaniyavagga": {
		"book": 22,
		"start": 73,
		"end": 82
	},
	"sn22-theravagga": {
		"book": 22,
		"start": 83,
		"end": 92
	},
	"sn22-pupphavagga": {
		"book": 22,
		"start": 93,
		"end": 102
	},
	"sn22-antavagga": {
		"book": 22,
		"start": 103,
		"end": 112
	},
	"sn22-dhammakathikavagga": {
		"book": 22,
		"start": 113,
		"end": 125
	},
	"sn22-avijjavagga": {
		"book": 22,
		"start": 126,
		"end": 135
	},
	"sn22-kukkulavagga": {
		"book": 22,
		"start": 136,
		"end": 149
	},
	"sn22-ditthivagga": {
		"book": 22,
		"start": 150,
		"end": 159
	},
	"sn23-pathamamaravagga": {
		"book": 23,
		"start": 1,
		"end": 10
	},
	"sn23-dutiyamaravagga": {
		"book": 23,
		"start": 11,
		"end": 22
	},
	"sn23-ayacanavagga": {
		"book": 23,
		"start": 23,
		"end": 34
	},
	"sn23-upanisinnavagga": {
		"book": 23,
		"start": 35,
		"end": 46
	},
	"sn24-sotapattivagga": {
		"book": 24,
		"start": 1,
		"end": 18
	},
	"sn24-dutiyagamanavagga": {
		"book": 24,
		"start": 19,
		"end": 44
	},
	"sn24-tatiyagamanavagga": {
		"book": 24,
		"start": 45,
		"end": 70
	},
	"sn24-catutthagamanavagga": {
		"book": 24,
		"start": 71,
		"end": 96
	},
	"sn25-cakkhuvagga": {
		"book": 25,
		"start": 1,
		"end": 10
	},
	"sn26-uppadavagga": {
		"book": 26,
		"start": 1,
		"end": 10
	},
	"sn27-kilesavagga": {
		"book": 27,
		"start": 1,
		"end": 10
	},
	"sn28-sariputtavagga": {
		"book": 28,
		"start": 1,
		"end": 10
	},
	"sn29-nagavagga": {
		"book": 29,
		"start": 1,
		"end": 50
	},
	"sn30-supannavagga": {
		"book": 30,
		"start": 1,
		"end": 46
	},
	"sn31-gandhabbavagga": {
		"book": 31,
		"start": 1,
		"end": 112
	},
	"sn32-valahakavagga": {
		"book": 32,
		"start": 1,
		"end": 57
	},
	"sn33-vacchagottavagga": {
		"book": 33,
		"start": 1,
		"end": 55
	},
	"sn34-jhanavagga": {
		"book": 34,
		"start": 1,
		"end": 55
	},
	"sn35-aniccavagga": {
		"book": 35,
		"start": 1,
		"end": 12
	},
	"sn35-yamakavagga": {
		"book": 35,
		"start": 13,
		"end": 22
	},
	"sn35-sabbavagga": {
		"book": 35,
		"start": 23,
		"end": 32
	},
	"sn35-jatidhammavagga": {
		"book": 35,
		"start": 33,
		"end": 42
	},
	"sn35-sabbaaniccavagga": {
		"book": 35,
		"start": 43,
		"end": 52
	},
	"sn35-avijjavagga": {
		"book": 35,
		"start": 53,
		"end": 62
	},
	"sn35-migajalavagga": {
		"book": 35,
		"start": 63,
		"end": 73
	},
	"sn35-gilanavagga": {
		"book": 35,
		"start": 74,
		"end": 83
	},
	"sn35-channavagga": {
		"book": 35,
		"start": 84,
		"end": 93
	},
	"sn35-salavagga": {
		"book": 35,
		"start": 94,
		"end": 103
	},
	"sn35-yogakkhemivagga": {
		"book": 35,
		"start": 104,
		"end": 113
	},
	"sn35-lokakamagunavagga": {
		"book": 35,
		"start": 114,
		"end": 123
	},
	"sn35-gahapativagga": {
		"book": 35,
		"start": 124,
		"end": 133
	},
	"sn35-devadahavagga": {
		"book": 35,
		"start": 134,
		"end": 145
	},
	"sn35-navapuranavagga": {
		"book": 35,
		"start": 146,
		"end": 155
	},
	"sn35-nandikkhayavagga": {
		"book": 35,
		"start": 156,
		"end": 167
	},
	"sn35-satthipeyyalavagga": {
		"book": 35,
		"start": 168,
		"end": 227
	},
	"sn35-samuddavagga": {
		"book": 35,
		"start": 228,
		"end": 237
	},
	"sn35-asivisavagga": {
		"book": 35,
		"start": 238,
		"end": 248
	},
	"sn36-sagathavagga": {
		"book": 36,
		"start": 1,
		"end": 10
	},
	"sn36-rahogatavagga": {
		"book": 36,
		"start": 11,
		"end": 20
	},
	"sn36-atthasatapariyayavagga": {
		"book": 36,
		"start": 21,
		"end": 31
	},
	"sn37-pathamapeyyalavagga": {
		"book": 37,
		"start": 1,
		"end": 14
	},
	"sn37-dutiyapeyyalavagga": {
		"book": 37,
		"start": 15,
		"end": 24
	},
	"sn37-balavagga": {
		"book": 37,
		"start": 25,
		"end": 34
	},
	"sn38-jambukhadakavagga": {
		"book": 38,
		"start": 1,
		"end": 16
	},
	"sn39-samandakavagga": {
		"book": 39,
		"start": 1,
		"end": 16
	},
	"sn40-moggallanavagga": {
		"book": 40,
		"start": 1,
		"end": 11
	},
	"sn41-cittavagga": {
		"book": 41,
		"start": 1,
		"end": 10
	},
	"sn42-gamanivagga": {
		"book": 42,
		"start": 1,
		"end": 13
	},
	"sn43-pathamavagga": {
		"book": 43,
		"start": 1,
		"end": 11
	},
	"sn43-dutiyavagga": {
		"book": 43,
		"start": 12,
		"end": 44
	},
	"sn44-abyakatavagga": {
		"book": 44,
		"start": 1,
		"end": 11
	},
	"sn45-avijjavagga": {
		"book": 45,
		"start": 1,
		"end": 10
	},
	"sn45-viharavagga": {
		"book": 45,
		"start": 11,
		"end": 20
	},
	"sn45-micchattavagga": {
		"book": 45,
		"start": 21,
		"end": 30
	},
	"sn45-patipattivagga": {
		"book": 45,
		"start": 31,
		"end": 40
	},
	"sn45-annatitthiyapeyyalavagga": {
		"book": 45,
		"start": 41,
		"end": 48
	},
	"sn45-suriyapeyyalavagga": {
		"book": 45,
		"start": 49,
		"end": 62
	},
	"sn45-ekadhammapeyyalavagga": {
		"book": 45,
		"start": 63,
		"end": 76
	},
	"sn45-dutiyaekadhammapeyyalavagga": {
		"book": 45,
		"start": 77,
		"end": 90
	},
	"sn45-gangapeyyalavagga": {
		"book": 45,
		"start": 91,
		"end": 102
	},
	"sn45-dutiyagangapeyyalavagga": {
		"book": 45,
		"start": 103,
		"end": 138
	},
	"sn45-appamadapeyyalavagga": {
		"book": 45,
		"start": 139,
		"end": 148
	},
	"sn45-balakaraniyavagga": {
		"book": 45,
		"start": 149,
		"end": 160
	},
	"sn45-esanavagga": {
		"book": 45,
		"start": 161,
		"end": 170
	},
	"sn45-oghavagga": {
		"book": 45,
		"start": 171,
		"end": 180
	},
	"sn46-pabbatavagga": {
		"book": 46,
		"start": 1,
		"end": 10
	},
	"sn46-gilanavagga": {
		"book": 46,
		"start": 11,
		"end": 20
	},
	"sn46-udayivagga": {
		"book": 46,
		"start": 21,
		"end": 30
	},
	"sn46-nivaranavagga": {
		"book": 46,
		"start": 31,
		"end": 40
	},
	"sn46-cakkavattivagga": {
		"book": 46,
		"start": 41,
		"end": 50
	},
	"sn46-sakacchavagga": {
		"book": 46,
		"start": 51,
		"end": 56
	},
	"sn46-anapanavagga": {
		"book": 46,
		"start": 57,
		"end": 66
	},
	"sn46-nirodhavagga": {
		"book": 46,
		"start": 67,
		"end": 76
	},
	"sn46-gangapeyyalavagga": {
		"book": 46,
		"start": 77,
		"end": 88
	},
	"sn46-appamadavagga": {
		"book": 46,
		"start": 89,
		"end": 98
	},
	"sn46-balakaraniyavagga": {
		"book": 46,
		"start": 99,
		"end": 110
	},
	"sn46-esanavagga": {
		"book": 46,
		"start": 111,
		"end": 120
	},
	"sn46-oghavagga": {
		"book": 46,
		"start": 121,
		"end": 130
	},
	"sn46-punagangapeyyalavagga": {
		"book": 46,
		"start": 131,
		"end": 142
	},
	"sn46-punaappamadavagga": {
		"book": 46,
		"start": 143,
		"end": 152
	},
	"sn46-punabalakaraniyavagga": {
		"book": 46,
		"start": 153,
		"end": 164
	},
	"sn46-punaesanavagga": {
		"book": 46,
		"start": 165,
		"end": 174
	},
	"sn46-punaoghavagga": {
		"book": 46,
		"start": 175,
		"end": 184
	},
	"sn47-ambapalivagga": {
		"book": 47,
		"start": 1,
		"end": 10
	},
	"sn47-nalandavagga": {
		"book": 47,
		"start": 11,
		"end": 20
	},
	"sn47-silatthitivagga": {
		"book": 47,
		"start": 21,
		"end": 30
	},
	"sn47-ananussutavagga": {
		"book": 47,
		"start": 31,
		"end": 40
	},
	"sn47-amatavagga": {
		"book": 47,
		"start": 41,
		"end": 50
	},
	"sn47-gangapeyyalavagga": {
		"book": 47,
		"start": 51,
		"end": 62
	},
	"sn47-appamadavagga": {
		"book": 47,
		"start": 63,
		"end": 72
	},
	"sn47-balakaraniyavagga": {
		"book": 47,
		"start": 73,
		"end": 84
	},
	"sn47-esanavagga": {
		"book": 47,
		"start": 85,
		"end": 94
	},
	"sn47-oghavagga": {
		"book": 47,
		"start": 95,
		"end": 104
	},
	"sn48-suddhikavagga": {
		"book": 48,
		"start": 1,
		"end": 10
	},
	"sn48-mudutaravagga": {
		"book": 48,
		"start": 11,
		"end": 20
	},
	"sn48-chalindriyavagga": {
		"book": 48,
		"start": 21,
		"end": 30
	},
	"sn48-sukhindriyavagga": {
		"book": 48,
		"start": 31,
		"end": 40
	},
	"sn48-jaravagga": {
		"book": 48,
		"start": 41,
		"end": 50
	},
	"sn48-sukarakhatavagga": {
		"book": 48,
		"start": 51,
		"end": 60
	},
	"sn48-bodhipakkhiyavagga": {
		"book": 48,
		"start": 61,
		"end": 70
	},
	"sn48-gangapeyyalavagga": {
		"book": 48,
		"start": 71,
		"end": 82
	},
	"sn48-appamadavagga": {
		"book": 48,
		"start": 83,
		"end": 92
	},
	"sn48-balakaraniyavagga": {
		"book": 48,
		"start": 93,
		"end": 104
	},
	"sn48-esanavagga": {
		"book": 48,
		"start": 105,
		"end": 114
	},
	"sn48-oghavagga": {
		"book": 48,
		"start": 115,
		"end": 124
	},
	"sn48-punagangapeyyalavagga": {
		"book": 48,
		"start": 125,
		"end": 136
	},
	"sn48-punaappamadavagga": {
		"book": 48,
		"start": 137,
		"end": 146
	},
	"sn48-punabalakaraniyavagga": {
		"book": 48,
		"start": 147,
		"end": 158
	},
	"sn48-punaesanavagga": {
		"book": 48,
		"start": 159,
		"end": 168
	},
	"sn48-punaoghavagga": {
		"book": 48,
		"start": 169,
		"end": 178
	},
	"sn49-gangapeyyalavagga": {
		"book": 49,
		"start": 1,
		"end": 12
	},
	"sn49-appamadavagga": {
		"book": 49,
		"start": 13,
		"end": 22
	},
	"sn49-balakaraniyavagga": {
		"book": 49,
		"start": 23,
		"end": 34
	},
	"sn49-esanavagga": {
		"book": 49,
		"start": 35,
		"end": 44
	},
	"sn49-oghavagga": {
		"book": 49,
		"start": 45,
		"end": 54
	},
	"sn50-gangapeyyalavagga": {
		"book": 50,
		"start": 1,
		"end": 12
	},
	"sn50-appamadavagga": {
		"book": 50,
		"start": 13,
		"end": 22
	},
	"sn50-balakaraniyavagga": {
		"book": 50,
		"start": 23,
		"end": 34
	},
	"sn50-esanavagga": {
		"book": 50,
		"start": 35,
		"end": 44
	},
	"sn50-oghavagga": {
		"book": 50,
		"start": 45,
		"end": 54
	},
	"sn50-punagangapeyyalavagga": {
		"book": 50,
		"start": 55,
		"end": 66
	},
	"sn50-punaappamadavagga": {
		"book": 50,
		"start": 67,
		"end": 76
	},
	"sn50-punabalakaraniyavagga": {
		"book": 50,
		"start": 77,
		"end": 88
	},
	"sn50-punaesanavagga": {
		"book": 50,
		"start": 89,
		"end": 98
	},
	"sn50-punaoghavagga": {
		"book": 50,
		"start": 99,
		"end": 108
	},
	"sn51-capalavagga": {
		"book": 51,
		"start": 1,
		"end": 10
	},
	"sn51-pasadakampanavagga": {
		"book": 51,
		"start": 11,
		"end": 20
	},
	"sn51-ayogulavagga": {
		"book": 51,
		"start": 21,
		"end": 32
	},
	"sn51-gangapeyyalavagga": {
		"book": 51,
		"start": 33,
		"end": 44
	},
	"sn51-appamadavagga": {
		"book": 51,
		"start": 45,
		"end": 54
	},
	"sn51-balakaraniyavagga": {
		"book": 51,
		"start": 55,
		"end": 66
	},
	"sn51-esanavagga": {
		"book": 51,
		"start": 67,
		"end": 76
	},
	"sn51-oghavagga": {
		"book": 51,
		"start": 77,
		"end": 86
	},
	"sn52-rahogatavagga": {
		"book": 52,
		"start": 1,
		"end": 10
	},
	"sn52-dutiyavagga": {
		"book": 52,
		"start": 11,
		"end": 24
	},
	"sn53-gangapeyyalavagga": {
		"book": 53,
		"start": 1,
		"end": 12
	},
	"sn53-appamadavagga": {
		"book": 53,
		"start": 13,
		"end": 22
	},
	"sn53-balakaraniyavagga": {
		"book": 53,
		"start": 23,
		"end": 34
	},
	"sn53-esanavagga": {
		"book": 53,
		"start": 35,
		"end": 44
	},
	"sn53-oghavagga": {
		"book": 53,
		"start": 45,
		"end": 54
	},
	"sn54-ekadhammavagga": {
		"book": 54,
		"start": 1,
		"end": 10
	},
	"sn54-dutiyavagga": {
		"book": 54,
		"start": 11,
		"end": 20
	},
	"sn55-veludvaravagga": {
		"book": 55,
		"start": 1,
		"end": 10
	},
	"sn55-rajakaramavagga": {
		"book": 55,
		"start": 11,
		"end": 20
	},
	"sn55-sarananivagga": {
		"book": 55,
		"start": 21,
		"end": 30
	},
	"sn55-punnabhisandavagga": {
		"book": 55,
		"start": 31,
		"end": 40
	},
	"sn55-sagathakapunnabhisandavagga": {
		"book": 55,
		"start": 41,
		"end": 50
	},
	"sn55-sappannavagga": {
		"book": 55,
		"start": 51,
		"end": 61
	},
	"sn55-mahapannavagga": {
		"book": 55,
		"start": 62,
		"end": 74
	},
	"sn56-samadhivagga": {
		"book": 56,
		"start": 1,
		"end": 10
	},
	"sn56-dhammacakkappavattanavagga": {
		"book": 56,
		"start": 11,
		"end": 20
	},
	"sn56-kotigamavagga": {
		"book": 56,
		"start": 21,
		"end": 30
	},
	"sn56-sisapavanavagga": {
		"book": 56,
		"start": 31,
		"end": 40
	},
	"sn56-papatavagga": {
		"book": 56,
		"start": 41,
		"end": 50
	},
	"sn56-abhisamayavagga": {
		"book": 56,
		"start": 51,
		"end": 60
	},
	"sn56-pathamaamakadhannapeyyalavagga": {
		"book": 56,
		"start": 61,
		"end": 70
	},
	"sn56-dutiyaamakadhannapeyyalavagga": {
		"book": 56,
		"start": 71,
		"end": 80
	},
	"sn56-tatiyaamakadhannapeyyalavagga": {
		"book": 56,
		"start": 81,
		"end": 90
	},
	"sn56-catutthaamakadhannapeyyalavagga": {
		"book": 56,
		"start": 91,
		"end": 101
	},
	"sn56-pancagatipeyyalavagga": {
		"book": 56,
		"start": 102,
		"end": 131
	}
};
